### ISSUE TITLE
1.10.2-2.0.1 - JEI Issue.

### ISSUE THREAD

**Issue by CurtisLee1994** [Morpheus1101/Avaritia#1]
Hey there.

Im working with Avaritia 1.10.2 and there seems to be a JEI issue. 
If you make a recipe and more then the top row is used when making the recipe the recipe does not show in JEI. 
If you make a recipe that only uses the top row nothing more, the recipe show. 

I hope this is enough information for you.

Working in JEI.
![25b956879a54ff43fb6fca82b9403c65](https://cloud.githubusercontent.com/assets/21251496/23312165/a218dd24-fab0-11e6-8b8e-2a0d7537a738.png)

Failing in JEI.
![88cd2f44286858530991a422d6c36776](https://cloud.githubusercontent.com/assets/21251496/23312168/a5c22002-fab0-11e6-8e8d-b13fde0b6ac8.png)

Here is the working code:
`mods.avaritia.ExtremeCrafting.addShaped(<avaritiaadditions:cosmic_meatballs>,
[[<avaritiaadditions:neutrons_pile>, <minecraft:beef>, <minecraft:beef>, <minecraft:chicken>, <minecraft:chicken>, <minecraft:porkchop>, <minecraft:porkchop>, <minecraft:fish>, <minecraft:fish>],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null]]);`

Here is none working code:
`mods.avaritia.ExtremeCrafting.addShaped(<avaritiaadditions:cosmic_meatballs>,
[[<avaritiaadditions:neutrons_pile>, <minecraft:beef>, <minecraft:beef>, <minecraft:chicken>, <minecraft:chicken>, <minecraft:porkchop>, <minecraft:porkchop>, <minecraft:fish>, <minecraft:fish>],
 [<minecraft:chicken>, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null],
 [null, null, null, null, null, null, null, null, null]]);`

**Comment by Morpheus1101** [comment]
Fixed in https://github.com/Morpheus1101/Avaritia/commit/e3ace5d2cfb3c8787f7e14c33beda50442242ce4
