### ISSUE TITLE
I was wondering how to make a item have halo noise same as neutronium ingot

### ISSUE THREAD

**Issue by RiniceSiberia** [Morpheus1101/Avaritia#103]
I am a modder

**Comment by covers1624** [comment]
It involves a bit of model trickery, https://github.com/Morpheus1101/Avaritia/blob/master/src/main/java/morph/avaritia/item/ItemResource.java#L135 As you can see there, basically we use some trickery inside CCL, HaloRenderItem takes a lambda, that lambda is fired before the list backing ModelRegistryHelper.register is called, this allows us to pull the model loaded from json, then replace it with the wrapped model that does the fancy halo stuffs. After doing that, the HaloRenderItem uses the interface IHaloRenderItem that should be applied to your item to see if it needs to render the halo, if so, gets the texture, size and colour. If you have any more questions feel free to ask here.
