### ISSUE TITLE
Avaritia (API) Problem !

### ISSUE THREAD

**Issue by TokyoSU** [Morpheus1101/Avaritia#107]
EDIT: Fail for close sorry :x
___
When i add latest avaritia version (3.2.0.9) or before,
he download the :
- JEI: old version
- CodeChickenLib: old version
- MineTweaker3: use CraftTweaker2
- ZenScript: old version
- asm-debug-all 5.0.3: old version (5.2 now)
- etc...

so after i test my mod, i get error when compile because all mods are in conflit !
___
image:
avaritia after dependencies added:
![avaritia_plugin](https://user-images.githubusercontent.com/27679699/41177047-def0e1d2-6b62-11e8-84a8-0dfbfcfb8a1c.PNG)

mymod dependencies:
![mymod_plugin](https://user-images.githubusercontent.com/27679699/41177106-1db8f198-6b63-11e8-9eb0-45504ea64e11.PNG)

dependencies of build:
![dependencies](https://user-images.githubusercontent.com/27679699/41177151-48b3cb3e-6b63-11e8-94cb-649ba1d41502.PNG)
___
when i delete avaritia dependenties (and classpath) all of line in first image dispear.
can you fix it please ?

**Comment by Morpheus1101** [comment]
What exactly are you trying to do? This version is for 1.12 an spitefulfox only works on the 1.7x version

**Comment by TokyoSU** [comment]
Need it for Singularity and Effect (Overlay).
if this version is not compatible for 1.12.2, you have probably a 1.12.2 version ?

**Comment by Morpheus1101** [comment]
This works as is on 1.12.x but is not compiled using 1.12.2 mapping but 1.12 mappings

**Comment by TokyoSU** [comment]
so what need for work on it in 1.12.2 with avaritia 1.12 ?

**Comment by Morpheus1101** [comment]
So you want to build a version, but not have any of the dependencies listed?

**Comment by TokyoSU** [comment]
No i just want it to use IHaloRenderItem for Singularity,
but avaritia 1.12 download all dependencies and i have all dependencies like codechickenlib already added in build.gradle but he download and ignore it !

**Comment by covers1624** [comment]
So whats happening here is due to gradle resolving dependencies. If you don't want Avaritia's transitive dependencies passed down you will need to do this.
```
deobfProvided ("morph.avaritia:Avaritia:${mc_version_old}-${mod_avaritia}:universal") {
    exclude group: "codechicken", module: "CodeChickenLib"
    //Insert any other things you want excluded here.
}
```
`./gradlew dependencies` is also your friend, it allows you to view and verify the dependency tree for the project. Also, viewing the .iml files is not really helpful in any way.
