### ISSUE TITLE
[1.10.2] Server & Client Crash Placing Resource Ore Blocks into Compressor

### ISSUE THREAD

**Issue by Morpheus1101** [Morpheus1101/Avaritia#11]
Crash Log: https://puu.sh/vsVTD/7047ab4825.txt

Only occurs using Non-Vanilla Ores

**Comment by MasterFee** [comment]
I added a recipe for the Diamond Singularity and it crashed too (used <ore:blockDiamond>).

Crash Log: https://pastebin.com/VrYhW2KR

**Comment by TheSpamMiner** [comment]
I had that too, it crashed for exactly the same reason.  If you want the crash log, I can put it, but it's almost identical to the ones here.
