### ISSUE TITLE
[1.12.2] Infinity Armor doesn't let you Jump higher

### ISSUE THREAD

**Issue by ToMe25** [Morpheus1101/Avaritia#110]
The Infinity Armor doesn't let doesn't let you Jump higher like the 1.7.10 one.

Tested with:
Minecraft version: 1.12.2
Minecraft Forge version: 14.23.4.2705
Avaritia Version: 3.2.0.25

**Comment by Morpheus1101** [comment]
In 1.7.10 The Boots by themselves let you jump higher than normal but for some reason since 1.1x ours do not which is a mystery of which i will blame brandon for

**Comment by Morpheus1101** [comment]
Fixed in Avaritia-1.12.2-3.3.0.28
