### ISSUE TITLE
[1.15] Damage entities at max damage, rather then killing them, (Mod Compatibility)

### ISSUE THREAD

**Issue by ryantheleach** [Morpheus1101/Avaritia#111]
https://github.com/Morpheus1101/Avaritia/blob/master/src/main/java/morph/avaritia/item/tools/ItemSwordInfinity.java#L60-L64

Would it be possible to change this code to instead of handling dead status yourself?

I believe if the damage is cancelled somehow, and the entity is to remain living, that code will still kill the entity right?

Could it not instead just deal max damage, or the entities current health, of a type that bypasses armor? (Like void damage does)

**Comment by ToMe25** [comment]
If you are doing something like this Please add a Config Option to re-enable the old behavior.

**Comment by ryantheleach** [comment]
@ToMe25 I'm interested in the reasoning why, having to endlessly support a config option adds additional drain, and you havn't provided a reason, and I can't see an obvious one and you have made me curious.

**Comment by Morpheus1101** [comment]
To clear up any confusion or misunderstanding, the intent for the sword is to kill everything and anything 1 hit, however, this ability is still being tweaked an some mod makers dont want you to be able to 1 hit there mobs, which is perfectly reasonable. This is being worked on, so plz have patience

**Comment by ToMe25** [comment]
@ryantheleach I want to stay able to one-hit some bosses(for example the Guardian of Gaia from Botania) with the Sword of Cosmos that can't be one-hit killed with "normal" Swords that's the Reason :)

**Comment by ryantheleach** [comment]
@ToMe25 By what mechanism is the Guardian of Gaia unable to be killed using normal swords? (resistant to all damage types?)

My suggestion **might** make it impossible for kill it using the blade, but I have a second suggestion that might fix that.

Most entities are susceptible to 'void' damage, that is the damage done to entities that stray below the world when falling into the void.

Avarita could attempt to do max damage, type void, which should bypass armor on nearly all modded and minecraft entities (if they are coded correctly)

If that fails to kill some special (or badly coded) modded entities, then it could do,

max damage of each of the damage types registered with the game (assuming they are registered!)

This would mean that as long as an entity somewhere is weak to **something** (and it's making that decision based on damage type) then the avarita blade would kill it (and remain compatible with any mod that purposely tries to prevent damage to entities, for protection, or force fields, or something that makes multiplayer friendly to public servers).

Yes some mods could get fancier with how they prevent damage, but if they are doing so they likely **don't** want their mobs being killed by the Sword of Cosmos.

It's pretty hard to be both compatible with protection mods, and able to kill absolutely everything.

In the end, it's a tradeoff that @Morpheus1101 and their team will have to make.

Do they want the Sword of Cosmos being banned on public servers for being OP / killing other peoples entities, and be able to kill everything? Or do they want it to be allowed on public servers, but unable to kill **some** entities that take special precautions to be difficult to kill.

**Comment by ToMe25** [comment]
> @ToMe25 By what mechanism is the Guardian of Gaia unable to be killed using normal swords? (resistant to all damage types?)

A "normal" meant a Sword that deals Player Attack Damage(damage Source Player), and those Swords can't one-hit kill the Guardian of Gaia.

**Comment by Morpheus1101** [comment]
This has been changed so it now does indeed deal max damage rather than setting the entity dead
