### ISSUE TITLE
Recipe won't produce Item but JEI says it should

### ISSUE THREAD

**Issue by Peach774** [Morpheus1101/Avaritia#112]
In JEI
https://cdn.discordapp.com/attachments/231527759279685634/482023932095102996/unknown.png

In Extreme Crafting Table
https://cdn.discordapp.com/attachments/231527759279685634/482024024038309889/unknown.png

Here is the code. All the of the words are using var word = <actualitemname>; to be defined.
ExtremeCrafting.addShaped("craft_tweaker_shaped_angelring", <extrautils2:angelring>, 
	[
		[null, null, goldblock, goldblock, goldblock, goldblock, goldblock, null, null], 
		[null, goldblock, matrixingot, matrixingot, gravititeblock, matrixingot, matrixingot, goldblock, null], 
		[goldblock, matrixingot, volatusphial, ravenfeather, aetherfeather, ravenfeather, volatusphial, matrixingot, goldblock], 
		[goldblock, matrixingot, ravenfeather, <botania:flighttiara>.withTag({}), flightmodule, valkyrieblock, ravenfeather, matrixingot, goldblock], 
		[goldblock, gravititeblock, aetherfeather, <actuallyadditions:item_wings_of_the_bats>, <extrautils2:chickenring:1>, <extrautils2:opinium:7>, aetherfeather, gravititeblock, goldblock], 
		[goldblock, matrixingot, ravenfeather, levitystaff, flightmodule, redhook, ravenfeather, matrixingot, goldblock], 
		[goldblock, matrixingot, volatusphial, ravenfeather, aetherfeather, ravenfeather, volatusphial, matrixingot, goldblock], 
		[null, goldblock, matrixingot, matrixingot, gravititeblock, matrixingot, matrixingot, goldblock, null], 
		[null, null, goldblock, goldblock, goldblock, goldblock, goldblock, null, null]
	]
);

**Comment by Peach774** [comment]
I tried getting rid of the variables and items with nbt tags - it still wont let me craft the item even though it shows up in JEI.

ExtremeCrafting.addShaped("Angel_Ring_Avaritia", <extrautils2:angelring>, 
	[
		[null, null, <minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>, null, null], 
		[null, <minecraft:gold_block>, <avaritia:resource:1>, <avaritia:resource:1>, <aether_legacy:enchanted_gravitite>, <avaritia:resource:1>, <avaritia:resource:1>, <minecraft:gold_block>, null], 
		[<minecraft:gold_block>, <avaritia:resource:1>, <thaumcraft:phial>, <twilightforest:raven_feather>, <aether_legacy:golden_feather>, <twilightforest:raven_feather>, <thaumcraft:phial>, <avaritia:resource:1>, <minecraft:gold_block>], 
		[<minecraft:gold_block>, <avaritia:resource:1>, <twilightforest:raven_feather>, <botania:flighttiara>, <rftools:flight_module>, <tinkersaether:valkyrie_block>, <twilightforest:raven_feather>, <avaritia:resource:1>, <minecraft:gold_block>], 
		[<minecraft:gold_block>, <aether_legacy:enchanted_gravitite>, <aether_legacy:golden_feather>, <actuallyadditions:item_wings_of_the_bats>, <extrautils2:chickenring:1>, <extrautils2:opinium:7>, <aether_legacy:golden_feather>, <aether_legacy:enchanted_gravitite>, <minecraft:gold_block>], 
		[<minecraft:gold_block>, <avaritia:resource:1>, <twilightforest:raven_feather>, <enderio:item_staff_of_levity>, <rftools:flight_module>, <hooked:hook:3>, <twilightforest:raven_feather>, <avaritia:resource:1>, <minecraft:gold_block>], 
		[<minecraft:gold_block>, <avaritia:resource:1>, <thaumcraft:phial>, <twilightforest:raven_feather>, <aether_legacy:golden_feather>, <twilightforest:raven_feather>, <thaumcraft:phial>, <avaritia:resource:1>, <minecraft:gold_block>], 
		[null, <minecraft:gold_block>, <avaritia:resource:1>, <avaritia:resource:1>, <aether_legacy:enchanted_gravitite>, <avaritia:resource:1>, <avaritia:resource:1>, <minecraft:gold_block>, null], 
		[null, null, <minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>, null, null]
	]
);

**Comment by Morpheus1101** [comment]
Can you upload a copy of the script somewhere that we are able to look at plz, as there seems to be a lot of missing < in this

**Comment by Peach774** [comment]
But, just for context: https://pastebin.com/2GTrNvCb

**Comment by Peach774** [comment]
Really need this fixed so I can use the recipes I’m making. All of the other features work fine, but it just won’t craft custom recipes.

**Comment by covers1624** [comment]
There seems to be some quirks with ntb crafting that are unfixable, ive reverted a change made to nbt crafting that just adds unnessesary code, perhaps that will have something to do with it, not sure. But basically there is no real generic way to have a fuzzy match on nbt, so sadly i can't do anything about this, you have to specify the full nbt of the item.

**Comment by Peach774** [comment]
I'm not sure this will fix it. I got some help on the modded minecraft discord, and at least in a dev environment, these changes seemed to work and allowed NBT to work as intended using Crafttweaker. Might i suggest just straight-up copying from the fork I was messing with?
https://github.com/Peach774/Avaritia

**Comment by covers1624** [comment]
Submit a PR and ill review the changes.

**Comment by Peach774** [comment]
#115

**Comment by Peach774** [comment]
Ignore all the weirdness. Thought the mod was possibly dead, so was forking as if I was going to have to publish it. I undid all of it

**Comment by Peach774** [comment]
I don’t want to seem rude, but it’s been a while. Could you provide an update on the status of the next version? I can’t release my pack until this is fixed

**Comment by Morpheus1101** [comment]
There has been a lot of other work occuring, but this hasnt been forgotten and will be addressed soon.

**Comment by covers1624** [comment]
https://github.com/Morpheus1101/Avaritia/commit/58927e7f9ab90a4fcd7b42041b3a79714dcb06e5  
Spoken with @Jaredlll08 about this one, Few things to note, `.withTag` should be used for modifying the NBT of the item displayed in JEI and `.onlyWithTag` should be used for Ingredient matching. Bit funky, but this issue should be fixed now.

**Comment by Morpheus1101** [comment]
Fixed in Avaritia-1.12.2-3.3.0.28

**Comment by solunareclipse1** [comment]
i have been having this issue recently, jei displays the recipe properly, but the table simply refuses to actually craft.

from what i can tell none of the items should have any form of nbt. ive tried to binary search the ingredients to find which one causes issues, that didnt work. also tried changing output and recipe name, neither of those worked either. i created an isolated instance with only avaritia, jei, crafttweaker, mods used in the recipe, the recipe itself, and any dependencies, issue persists. crafttweaker.log doesnt seem to output any errors, and quite frankly im at a loss.

screenshots: https://imgur.com/a/5r4DU9I
offending script: https://pastebin.com/dq1xtLrv
crafttweaker.log: https://pastebin.com/TMHQjShU
latest.log: https://hatebin.com/hrgmwolshs (pastebin stopped working for some reason)

mods list, as output by /ct mods:
minecraft - Minecraft - 1.12.2
mcp - Minecraft Coder Pack - 9.42
FML - Forge Mod Loader - 8.0.99.99
forge - Minecraft Forge - 14.23.5.2855
micdoodlecore - Micdoodle8 Core - 
aether_legacy - The Aether - 1.5.3.1
baubles - Baubles - 1.5.2
crafttweaker - CraftTweaker2 - 4.1.20
astralsorcery - Astral Sorcery - 1.10.27
autoreglib - AutoRegLib - 1.3-32
codechickenlib - CodeChicken Lib - 3.2.3.358
avaritia - Avaritia - 3.3.0
jei - Just Enough Items - 4.16.1.302
thaumcraft - Thaumcraft - 6.1.BETA26
botania - Botania - r1.10-363
patchouli - Patchouli - 1.0-23.6
bewitchment - Bewitchment - 0.22.59
guideapi - Guide-API - 1.12-2.1.8-63
bloodmagic - Blood Magic: Alchemical Wizardry - 1.12.2-2.4.3-105
redstoneflux - Redstone Flux - 2.1.1
brandonscore - Brandon's Core - 2.4.19
chickenchunks - ChickenChunks - 2.4.2.74
cofhcore - CoFH Core - 4.6.6
cofhworld - CoFH World - 1.4.0
refinedstorage - Refined Storage - 1.6.16
compactmachines3 - Compact Machines 3 - 3.0.18
ctgui - CT-GUI - 1.0.0
crafttweakerjei - CraftTweaker JEI Support - 2.0.3
ctm - CTM - MC1.12.2-1.0.2.31
roots - Roots - 1.12.2-3.0.32
mysticalworld - Mystical World - 1.12.2-1.9.2
endercore - EnderCore - 1.12.2-0.5.76
thermalfoundation - Thermal Foundation - 2.6.7
enderio - Ender IO - 5.2.66
enderiointegrationtic - Ender IO Integration with Tinkers' Construct - 5.2.66
mantle - Mantle - 1.12-1.3.3.55
twilightforest - The Twilight Forest - 3.11.1021
tconstruct - Tinkers' Construct - 1.12.2-2.13.0.183
deepmoblearning - Deep Mob Learning - 1.12.2-2.5.4
draconicevolution - Draconic Evolution - 2.3.27
embers - Embers Rekindled - 1.17
enderiobase - Ender IO Base - 5.2.66
enderioconduits - Ender IO Conduits - 5.2.66
enderioconduitsappliedenergistics - Ender IO Applied Energistics Conduits - 5.2.66
enderioconduitsopencomputers - Ender IO Open Computers Conduits - 5.2.66
enderioconduitsrefinedstorage - Ender IO Refined Storage Conduits - 5.2.66
enderiointegrationforestry - Ender IO Integration with Forestry - 5.2.66
enderiointegrationticlate - Ender IO Integration with Tinkers' Construct - 5.2.66
enderioinvpanel - Ender IO Inventory Panel - 5.2.66
enderiomachines - Ender IO Machines - 5.2.66
enderiopowertools - Ender IO Powertools - 5.2.66
enderioendergy - Ender IO endergy - 5.2.66
hammercore - Hammer Core - 2.0.6.26
projecte - ProjectE - 1.12.2-PE1.4.1
equivadditions - Equivalent Additions - 12.2.9
ic2 - IndustrialCraft 2 - 2.8.221-ex112
galacticraftcore - Galacticraft Core - 4.0.2.281
galacticraftplanets - Galacticraft Planets - 4.0.2.281
mcjtylib_ng - McJtyLib - 3.5.4
metallurgy - Metallurgy 4: Reforged - 1.2.4
mekanism - Mekanism - 1.12.2-9.8.3.390
mekanismgenerators - Mekanism: Generators - 1.12.2-9.8.3.390
mekanismtools - Mekanism: Tools - 1.12.2-9.8.3.390
psi - Psi - r1.1-78
reborncore - Reborn Core - 3.19.4.529
rebornstorage - RebornStorage - 1.0.0
rftools - RFTools - 7.73
thaumicaugmentation - Thaumic Augmentation - 1.12.2-2.0.13
mysticallib - Mystical Lib - 1.12.2-1.9.0

**Comment by Morpheus1101** [comment]
We are no longer working on 1.12x as 1.16x is Under Development.

**Comment by solunareclipse1** [comment]
alright fair enough
