### ISSUE TITLE
nuetromium compressor disabled

### ISSUE THREAD

**Issue by TheNimbleNinja** [Morpheus1101/Avaritia#113]
all the singularitys are disabled or dont have a recipe and the nuetronium compressor is disabled and i dont know why i cant find out anywhere why its disabled this is my last hope that you will know why its gone plkease help

**Comment by Morpheus1101** [comment]
Have you tried to delete the config for Avaritia and then tried ?

**Comment by TheNimbleNinja** [comment]
i tried that and it still is disabled

**Comment by Morpheus1101** [comment]
Are u using this in a modpack ?

**Comment by covers1624** [comment]
Your modpack is disabling the block, it is indeed craftable, furthermore we don't even have a config to disable it.
