### ISSUE TITLE
[1.12.2] Wings emitted by the Infinity Armor aren't visible from behind.

### ISSUE THREAD

**Issue by oGennyo** [Morpheus1101/Avaritia#116]
https://gyazo.com/0376d090cbe27413f874339fa5e5da55 Here's a pic of the problem. Can see them perfectly from the front, not so much the back. Thought it was optifine but I removed it and the issue persisted.

**Comment by oGennyo** [comment]
Yep. Removed all mods to check again. Issue is still present. Could it be the version of forge or codechickenlib?

**Comment by p455w0rd** [comment]
Yeah, I noticed this on OG_arist0tle's stream last night

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ if this issue is present when the new version has been released, feel free to re-open this ticket.
