### ISSUE TITLE
[1.12.2] Error Messages in Minecraft Log

### ISSUE THREAD

**Issue by realTIMematrix** [Morpheus1101/Avaritia#118]
Hi,
i receive some texture error messages and loading model errors. Is this important or can i ignore this?

- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 176185832 bytes (168 MB) / 730857472 bytes (697 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 980/PCIe/SSE2'

Minecraft: 1.12.2
Forge: 14.23.5.2768
Avaritia 1.12.2-3.2.0.25
CodeChicken Lib 1.8.+ 1.12.2-3.2.2.353

Errors:
Exception loading model for variant avaritia:infinity_bow#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:item/infinity_bow with loader VanillaLoader.INSTANCE, skipping

Exception loading model for variant avaritia:infinity_bow#inventory, blockstate location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:infinity_bow#inventory with loader VariantLoader.INSTANCE, skipping

Exception loading model for variant avaritia:infinity_hoe#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:item/infinity_hoe with loader VanillaLoader.INSTANCE, skipping

Exception loading model for variant avaritia:infinity_hoe#inventory, blockstate location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:infinity_hoe#inventory with loader VariantLoader.INSTANCE, skipping

Exception loading model for variant avaritia:infinity_sword#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:item/infinity_sword with loader VanillaLoader.INSTANCE, skipping

Exception loading model for variant avaritia:infinity_sword#inventory, blockstate location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:infinity_sword#inventory with loader VariantLoader.INSTANCE, skipping

And:

`
15:56:15 | FML.TEXTURE_ERRORS | main | error | +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
-- | -- | -- | -- | --
15:56:15 | FML.TEXTURE_ERRORS | main | error | The following texture errors were found.
15:56:15 | FML.TEXTURE_ERRORS | main | error | ==================================================
15:56:15 | FML.TEXTURE_ERRORS | main | error | DOMAIN minecraft
15:56:15 | FML.TEXTURE_ERRORS | main | error | --------------------------------------------------
15:56:15 | FML.TEXTURE_ERRORS | main | error | domain minecraft is missing 1 texture
15:56:15 | FML.TEXTURE_ERRORS | main | error | domain minecraft has 1 location:
15:56:15 | FML.TEXTURE_ERRORS | main | error | unknown resourcepack type net.minecraft.client.resources.DefaultResourcePack : Default
15:56:15 | FML.TEXTURE_ERRORS | main | error | -------------------------
15:56:15 | FML.TEXTURE_ERRORS | main | error | The missing resources for domain minecraft are:
15:56:15 | FML.TEXTURE_ERRORS | main | error | textures/missingno.png
15:56:15 | FML.TEXTURE_ERRORS | main | error | -------------------------
15:56:15 | FML.TEXTURE_ERRORS | main | error | No other errors exist for domain minecraft
15:56:15 | FML.TEXTURE_ERRORS | main | error | ==================================================
15:56:15 | FML.TEXTURE_ERRORS | main | error | +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

`

**Comment by Morpheus1101** [comment]
You can ignore it
