### ISSUE TITLE
ultimate stew is not craftable

### ISSUE THREAD

**Issue by gustaff67** [Morpheus1101/Avaritia#119]
version 1.12 with pamharvestcraft JEI put the items in the table for me and it shows that the recepie is for the ultimate stew is right but i do not work

**Comment by Morpheus1101** [comment]
Can you show me a picture of the crafting table with all ingredients in it plz

**Comment by gustaff67** [comment]
![screenshot 2018-10-26 14 36 44](https://user-images.githubusercontent.com/34782053/47567820-d250c880-d92f-11e8-9612-dbb10b19bf84.png)
![screenshot 2018-10-26 14 43 44 4](https://user-images.githubusercontent.com/34782053/47567822-d250c880-d92f-11e8-89a7-ffc418a845e7.png)
![screenshot 2018-10-26 14 43 45](https://user-images.githubusercontent.com/34782053/47567823-d250c880-d92f-11e8-9b6f-0fa444663204.png)
![screenshot 2018-10-26 14 46 35](https://user-images.githubusercontent.com/34782053/47567825-d250c880-d92f-11e8-8e01-2a244cce0a6c.png)
![screenshot 2018-10-26 14 55 58](https://user-images.githubusercontent.com/34782053/47567827-d2e95f00-d92f-11e8-9af9-382eaadf5dd4.png)
![screenshot 2018-10-26 14 56 48](https://user-images.githubusercontent.com/34782053/47567828-d2e95f00-d92f-11e8-8a96-54ad75ce4ab0.png)

**Comment by covers1624** [comment]
I'm unable to reproduce this issue. 
![](https://ss.covers1624.net/3d41f)

**Comment by Morpheus1101** [comment]
![2018-12-14_07 51 43](https://user-images.githubusercontent.com/10524952/49969792-2877da80-ff75-11e8-88cd-7980311a9529.png)

![ultstew](https://user-images.githubusercontent.com/10524952/49969842-4b09f380-ff75-11e8-8899-9519f0e2f2fd.png)

**Comment by covers1624** [comment]
I believe a commit i reverted a little while ago fixed this issue.
