### ISSUE TITLE
Endest pearl events

### ISSUE THREAD

**Issue by mr2013** [Morpheus1101/Avaritia#122]
Endest pearl should trigger BlockEvent.BreakEvent and AttackEntityEvent and respect cancelled so as to allow anti-griefing mods to do their job

**Comment by covers1624** [comment]
BreakEvent's are now fired using avaritia's FakePlayer, its not possible to sanely keep context as to what player threw the Pearl so AttackEvent will not be happening.

**Comment by covers1624** [comment]
No problem, also here we keep the issue open until a release has been made including the fix.

**Comment by Morpheus1101** [comment]
Fixed in Avaritia-1.12.2-3.3.0.28
