### ISSUE TITLE
Unknown Craftweaker Error

### ISSUE THREAD

**Issue by HardInk** [Morpheus1101/Avaritia#125]
Added Item Recipe for Extreme Table, Item Recipe constructed properly but Item cannot be crafted In table, but can be made using a refined storage automated crafter. Initial recipe was supposed to be removed but wasn't.
[SingularityBoi.zip](https://github.com/Morpheus1101/Avaritia/files/2705777/SingularityBoi.zip)

**Comment by Morpheus1101** [comment]
To sum up what he is trying to say... The script is fine and loads an dosent work only due to Thaumcraft Primordial Pearl. With the Avaritia addon for RS the 9x9 recipe works fine just dosent in the ExtremeCrafting Table.

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ if this issue is present when the new version has been released, feel free to re-open this ticket.
