### ISSUE TITLE
Currently missing features

### ISSUE THREAD

**Issue by Froggy800** [Morpheus1101/Avaritia#13]
Just a list of currently missing features that you may or may not be aware of:
-Nature's Ruin is missing its shift-right click aoe mining; the axe always digs in an aoe and it only drops the first block mined
-Planet Eater and World Breaker's destroyer modes do nothing but slow down the block breaking speed
-World Breaker cannot mine bedrock, regardless of the config
-Matter clusters are not implemented (or maybe they are, but I have no way to know since the area mining isn't working)
Tested on Avaritia version 2.1.0.1 and Forge version 12.18.3.2254

**Comment by covers1624** [comment]
Valid issues, Most of that is due to the AOE pickup code being total cancer, Will be reworked soon.
