### ISSUE TITLE
[Suggestion] Singularity destabilizer

### ISSUE THREAD

**Issue by scribbler957** [Morpheus1101/Avaritia#131]
I think it's Nuclear Craft that has simple blocks that create 20mb or water or 20 pieces of cobble a tick. It gave me an idea, at some point you've collected enough stuff that you should be able to just generate more. You've made enough mines, lasers, mob farms, and mystical agriculture cloches and now you can save the server some lag by tearing it down to make a single block that generates 20 nuggets of gold per tick (or whatever, a destabilized chicken singularity sounds like fun).

**Comment by scribbler957** [comment]
I had a thought of a machine that had to build a custom singularity by taking in the correct amount of the material in question, but also other materials that add mass, balance, and destabilize. The trick is there's only 1 input and if it gets out of balance (too many more of one of the ingredients) it starts to decay causing undocumented material loss which makes it more unstable and harder to bring back into balance. (The materials need to be fed in a certain pattern or order, if the ratio goes off by more than 0.1%...)
Make the player prove they can create monstrous amounts of resources in a reasonable time frame, make them work hard at the balancing game and reward them for it.
(I'll put it in my mod ideas Gist in case you don't think it fits.)

**Comment by Morpheus1101** [comment]
Its an interesting concept, its something i can think an discuss over, but fo rnow i'll leave it as a possability and see what happens.

**Comment by scribbler957** [comment]
Fair enough. Thank you for your consideration and hard work.
Feel free to tag or close the idea as fits your workflow.

**Comment by Morpheus1101** [comment]
While i still feel this is an intriguing concept, at this stage i dont feel its a good fit...but i will keep it on my local possibilities list.
