### ISSUE TITLE
[Suggestion] Add the Asgardandelion flower from original 1.7.10 mod

### ISSUE THREAD

**Issue by NOTMASTER09** [Morpheus1101/Avaritia#132]
I know about avaritia tweaks mod,but i don't want to install a discontinued mod

**Comment by Morpheus1101** [comment]
we'll be looking at a lot of the old stuff from 1.7.10 to re-add into the newer vers once we establish if we're going to stick with forge or go skip an use Fabric instead

**Comment by Tfarcenim** [comment]
Avaritias Complement is an actively maintained fork of Avaritia Tweaks, direct any bug reports/feature requests there https://minecraft.curseforge.com/projects/avaritia-complement
