### ISSUE TITLE
Extrabotany gaia guradian 3 defense

### ISSUE THREAD

**Issue by NOTMASTER09** [Morpheus1101/Avaritia#134]
There is a problem in the mod.The gaia guradian 3 is intended to fight only with vanilla or botania items,any other items just was dropper out.But the infinity armor is intended to be dropped only by player's hand.

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ if this issue is present when the new version has been released, feel free to re-open this ticket.
