### ISSUE TITLE
[1.12.2]CraftTweaker dont work script

### ISSUE THREAD

**Issue by alesha229** [Morpheus1101/Avaritia#135]
```
mods.avaritia.Compressor.remove(<avaritia:singularity>);
mods.avaritia.Compressor.add(<avaritia:singularity>, 5000, <minecraft:iron_block>, false);
```

[INITIALIZATION][CLIENT][ERROR] Recipes.zs:27 > a method available but none matches the parameters (ZenTypeNative: crafttweaker.item.IItemStack, int, ZenTypeNative: crafttweaker.item.IItemStack, bool)
This is usually an error in your script, not in the mod
add(string, ZenTypeNative: crafttweaker.item.IItemStack, int, ZenTypeNative: crafttweaker.item.IIngredient, Optional bool)
Last craft deleted,but new craft make error.
I found this and just copy to my script
https://pastebin.com/HJj5tsSi
But it don`t work too.

**Comment by Rumaruka** [comment]
` public static void add(String name, IItemStack output, int amount, IIngredient input, @Optional boolean absolute)`
Try
mods.avaritia.Compressor.add("test",<avaritia:singularity>, 5000, <minecraft:iron_block>, false);

**Comment by Morpheus1101** [comment]
If this is still an issue plz let me know
