### ISSUE TITLE
[Suggestion] Add new world breaker mechanic

### ISSUE THREAD

**Issue by NOTMASTER09** [Morpheus1101/Avaritia#136]
Mechanic is like this: when yo get two hammer mode world breaker in main hand an off hand you start to mine 30x30

**Comment by Morpheus1101** [comment]
You cant mine using your off hand only main hand.

**Comment by NOTMASTER09** [comment]
I mean that the world breaker will check if there is world breaker in offhand and start mining 30x30.

**Comment by Morpheus1101** [comment]
I appreciate the suggestion, but i dont see it as viable sorry.
