### ISSUE TITLE
Infinity Armor is rendered reversed on the vanilla Armor Stand

### ISSUE THREAD

**Issue by ben-mkiv** [Morpheus1101/Avaritia#137]
version 3.3.0

![](https://i.imgur.com/2Psw0rR.png)
![](https://i.imgur.com/05ZEK41.png)

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ if this issue is present when the new version has been released, feel free to re-open this ticket.
