### ISSUE TITLE
Breaking the chaos crystal with world breaker

### ISSUE THREAD

**Issue by adstheorganic** [Morpheus1101/Avaritia#138]
I'm playing with the latest version of avaritia and draconic evolution  for 1.12.2 and when breaking the chaos crystal with the world breaker in its default mode it gave me an un-textured chaos crystal instead of the 20 shards it was supposed to, breaking it in its hammer form give the crystals correctly though, It's like it's doing some weird silk touch even though it has fortune x. This only happens when you haven't killed the dragon, but because it works in hammer mode It could be a bug with either avaritia or draconic evolution from the testing.

**Comment by adstheorganic** [comment]
This is because I was not killing the chaos guardian first and the world breaker allows you to do that, so I imagine its a draconic evolution bug instead

**Comment by Morpheus1101** [comment]
Both Avaritia and Draconic Evolution are Undergoing a Complete re-write for 1.15+ if this issue is present when the new versions of both mods have been released, feel free to re-open this ticket.
