### ISSUE TITLE
[1.10.2] Changing dimension disables step assist

### ISSUE THREAD

**Issue by Froggy800** [Morpheus1101/Avaritia#14]
After going to The Nether / The End the Infinity Boots' step assist stops working; the same happens when you go back to the overworld. Restarting the game or re-equipping the boots fixes the problem.
Tested on Avaritia version 2.1.0.1 and Forge version 12.18.3.2254

**Comment by Morpheus1101** [comment]
End/Nether i can confirm, however returning to overworld for me the step assist continues to work again.

**Comment by Froggy800** [comment]
That's weird... I've been able to reproduce this very consistently for each of the three vanilla dimensions, both with and without other mods installed.
Out of curiosity I made a separate test by adding the Random Things mod and going to the spectre dimension - the step assist stopped working there as well; I guess this isn't even dimension related.

**Comment by Morpheus1101** [comment]
The Cause of this is known and we should be releasing a fix sometime today/tommorow
