### ISSUE TITLE
Cant open CraftingTable NoSuchMethodError

### ISSUE THREAD

**Issue by Likqez** [Morpheus1101/Avaritia#140]
Hey, i got a Problem with the Extreme Crafting Table,
I cant open the Table and i just get this Error.
Error: https://hasteb.in/nulupala.kotlin

Thanks for help.

**Comment by Morpheus1101** [comment]
What MC Vers, 1.12.2? and if this crashed, i will need full crash log.

**Comment by Likqez** [comment]
1.12.2, and no the server did not crash.

**Comment by Morpheus1101** [comment]
I tested this myself with just Avaritia, ccl, journeymap & JEI an it worked fine with no errors occuring...is this being used in a pack ?

**Comment by Likqez** [comment]
If you want reproduce it, I am playing on a pack on technic launcher: Texxit by Likqez

Just try it out. Thanks
