### ISSUE TITLE
World Breaker in Hammer Mode can mine bedrock

### ISSUE THREAD

**Issue by ben-mkiv** [Morpheus1101/Avaritia#141]
Looks like the World Breaker ignores the Harvest Level of Blocks when used in Hammer Mode.

So if you mine one layer above Bedrock it'll mine the underlaying bedrock layer, too

https://i.imgur.com/ahpHcMf.png

edit: actually you can also hit the bedrock from above to mine it.

mod version: 3.3.0

**Comment by brachy84** [comment]
It is supposed to be like that
