### ISSUE TITLE
[Suggestion] Tool and Armor features

### ISSUE THREAD

**Issue by ghost** [Morpheus1101/Avaritia#143]
-Make tools and armor immune to /clear commands
-Give armor full knockback resistance
-Give sword longer reach
-Give bow instant drawspeed and no arrow falloff
-Right-clicking with the sword can result in a "kill aura" effect that kills all entities within a configurable radius

**Comment by Morpheus1101** [comment]
1. No
2. Should all ready exist, will look into it
3. Reach shouldnt be anymore than a dia sword, but will discuss this as a possability
4. Will discuss as a possability
5. No

**Comment by qzzz00000** [comment]
Is there an argument against 3 and 5? Honestly the sword is OP enough that these features would be fine IMO.
