### ISSUE TITLE
Bow QOL improvements and enhancements

### ISSUE THREAD

**Issue by ghost** [Morpheus1101/Avaritia#149]
So I came up with some ideas for the bow that would be pretty cool, do consider :) 

-infinite arrow velocity, something like extra utilities compound bow (for easier aiming) 
-instant drawspeed
-toggle-able "auto shoot" like the draconic evolution bow? To make arrow rain lol

**Comment by Morpheus1101** [comment]
Bow and its function have been completely re-written an changed
