### ISSUE TITLE
Recipe Glitching

### ISSUE THREAD

**Issue by SextupleTap** [Morpheus1101/Avaritia#152]
This is a very weird encounter I had with a Avaritia recipe I added:

Recipe:
https://pastebin.com/XFczRXhs

Basically when I load in the recipe, the first 5 rows load properly, but then the last 3 rows have the order of the items shifted to the left by 1 item, and then the last final rows has the same effect but the 9th slot on the bottom right corner is missing a pile of neutrons so it skipped the 9th ingredient (yes all the "vals" are properly registered and before the script too)

Visual:
https://imgur.com/a/UNAKIMK

Craft Tweaker Log:
https://pastebin.com/sKkPJAMq

Latest Log:
https://pastebin.com/aQPq4dBU

Avaritia:
1.12.2-3.3.0.33

Forge:
14.23.5.2838

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write as is the recipe system for 1.15+ if this issue is present when the new version has been released, feel free to re-open this ticket.
