### ISSUE TITLE
[Question] How to add items to infinity catalyst recipe without CraftTweaker/MineTweaker

### ISSUE THREAD

**Issue by TheUnderTaker11** [Morpheus1101/Avaritia#153]
This is for an addon mod I make, More Avaritia.                
Only way I've seen is to use your CraftTweaker compat to delete the old infinity catalyst recipe and add a new one but with added in item(s). Doubt this is ideal, as it adds craft tweaker to the registry name.

Also adding what all I said in Discord about this cause it might be useful info?
![image](https://user-images.githubusercontent.com/16872377/65064533-492af180-d946-11e9-9420-c6aa9ae71f19.png)

**Comment by TheUnderTaker11** [comment]
I've also tried this, and the commented out line I tried inside the get as well.
![image](https://user-images.githubusercontent.com/16872377/65065560-43cea680-d948-11e9-98e8-daaaccadd3e5.png)

**Comment by covers1624** [comment]
Yeah deleting the recipe and adding it back is likely not ideal. You can use the Registry event for recipes and add the ingredients directly, just make sure you specify a lower priority than avaritia (i believe its no Normal as its the default).
This is something that can be looked into in the future as some sort of API endpoint.
