### ISSUE TITLE
Incompatible with the Shaders: Sildrus Vibrant Shaders 1.23

### ISSUE THREAD

**Issue by COD3BREAK3R** [Morpheus1101/Avaritia#155]
Hello, thanks for creating this great mod, I would like if it is possible to solve the texture problems of this mod with the sildrus shaders that I mentioned in the title of the issue because it turns out that by wearing the full armor of this mod and having The shaders that I mentioned earlier happen that the character becomes transparent almost completely, affecting other mods such as the wings mod, it also presents lighting problems with items such as the sword and it seems to me that also with the beak and others, this problem I already reported it on the Sildrus Vibrant Shaders forum, anyway I put it here anyway:

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291396-1-7-10-1-14-4-sildurs-shaders-pc-mac-intel?comment=5811

**Comment by covers1624** [comment]
Nothing we can fix on our end, sadly it's just an incompatibility.
