### ISSUE TITLE
[Bug] [1.12.2] Sword of the Cosmos is blocked by a vanila Shield

### ISSUE THREAD

**Issue by NikeSchuh** [Morpheus1101/Avaritia#158]
Version : 1.12.2
Avaritia : Avaritia-1.12.2-3.3.0.33-universal.jar

The Vanilla Shield can block the hit of the Sword of the Cosmos.
Also its completly blocked by the Terraprotector of Botanic Additions.

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ if this issue is present when the new version has been released, feel free to re-open this ticket.
