### ISSUE TITLE
[Request] JSON to create custom singularities 

### ISSUE THREAD

**Issue by TokkenGmr** [Morpheus1101/Avaritia#16]
I was wondering if it might be possible to have JSON files that would allow pack creators to create custom singularities?

**Comment by TheSpamMiner** [comment]
Or even a spot in the config for an item or block to use, an rgb color, and a base value for the amount required. There's something kinda like it in the 1.11 mod Overloaded, where you can add custom blocks to compress, and to what level.

**Comment by tyler489** [comment]
I would love the rgb values thing...

**Comment by TheSpamMiner** [comment]
Ooh, and making them automatically added to the recipe would be amazing.
