### ISSUE TITLE
Abyssalcraft j'zahar damagin the player with the infinity set

### ISSUE THREAD

**Issue by ios777** [Morpheus1101/Avaritia#160]
minecraft version:1.12.2
avaritia version:3.3.0

Detail:
There are 2 ways j'zahar can damage you: the frist is with his body explosion. I got damaged after it losing more then half healt.
The second is when evoked in creative using commandline with the infiniy armor on. after damaging him with a sword that doesn't insta-kill him (not the sword of cosmo) he will eventually switch your gamemode to survival and one shot kill you.

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ if this issue is present when the new version of both these mods has been released, feel free to re-open this ticket.
