### ISSUE TITLE
[1.12]Neutronium Ingots in Drawers are viable through blocks

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Morpheus1101/Avaritia#162]
Avaritia Version: 3.3.0
StorageDrawers version: 1.12.2-5.3.8

Neutronium ingots being stored in storage drawers are visible through blocks, as seen in the included image.
![2020-02-07_18 46 05](https://user-images.githubusercontent.com/31759736/74077329-2922ca00-49dc-11ea-8154-3368019ec9b3.png)

This is actually this image, seen from a different angle, with blocks in between.
![2020-02-07_19 01 02](https://user-images.githubusercontent.com/31759736/74077337-4788c580-49dc-11ea-8dcb-663aafe64914.png)

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ if this issue is present when the new version has been released, feel free to re-open this ticket.
