### ISSUE TITLE
My world crashes after cheating in a Matter Cluster 

### ISSUE THREAD

**Issue by hudsonrockes** [Morpheus1101/Avaritia#163]
[Pastebin](https://pastebin.com/vGyDaQ84)

**Comment by Morpheus1101** [comment]
What pack is this your using?

**Comment by hudsonrockes** [comment]
> What pack is this your using?

I made a custom back

**Comment by Morpheus1101** [comment]
Avaritia is Undergoing a Complete re-write for 1.15+ this particular feature of the mod is not planned to be continued moving forward.
