### ISSUE TITLE
I have a problem with avarita and enderio pls help GAME NOT START UP Get an error

### ISSUE THREAD

**Issue by CriticalReturnZz** [Morpheus1101/Avaritia#167]
when i start Minecraft with Avaritia and Ender IO i get a massage " Unknow " Avarita is potentiel casuel

there is Crash report : 
[crash-2020-06-17_11.58.26-client.txt](https://github.com/Morpheus1101/Avaritia/files/4791837/crash-2020-06-17_11.58.26-client.txt)

**Comment by Morpheus1101** [comment]
Fractured Ores should be disabled by default as it is broken and likely to be removed in the new version. Go back into the config and disable fractured ores and that should solve the issue your having.
