### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by Gunni** [Morpheus1101/Avaritia#168]
Hey,

I love the Infinity Armor but despise the auto-step feature.

I'd like to be able to turn it off, while still keeping the armor set on...

Thanks

Originally made this ticket in the wrong repo, here: https://github.com/SpitefulFox/Avaritia/issues/146

**Comment by Gunni** [comment]
Basically lines:
- https://github.com/Morpheus1101/Avaritia/blob/9875f1cf518786be94101608d1dc0589776c18fa/src/main/java/morph/avaritia/handler/AbilityHandler.java#L166
- https://github.com/Morpheus1101/Avaritia/blob/9875f1cf518786be94101608d1dc0589776c18fa/src/main/java/morph/avaritia/handler/AbilityHandler.java#L220

Need additional conditions, but I don't really know how you could add in a boolean there.

**Comment by Morpheus1101** [comment]
This is a planned feature to be added in 1.16x

**Comment by Gunni** [comment]
I did succeed in disabling it by editing the class file using a bytecode editor and simply NOPing the instructions that modify stepHeight.

Even works in multiplayer :D

Yay it's usable!
