### ISSUE TITLE
Ultimate stew lost content

### ISSUE THREAD

**Issue by Nanamiya738** [Morpheus1101/Avaritia#169]
Avaritia：1.12.2-3.3.0.33
Forge：1.12.2 14.23.5.2854
CodeChicken Lib： 1.12.2 3.2.3.358-universal

I can craft Cosmic Meatballs, but it fave some bug that put item by JEI's recipe but I get nothing in result slot.

**Comment by Morpheus1101** [comment]
Using the 3 mods you listed, i wasnt able to re-produce this issue. JEI placed everything into the table quite fine
