### ISSUE TITLE
Unable to see and craft Avaritia Dire Crafting Table outputs

### ISSUE THREAD

**Issue by matt091498** [Morpheus1101/Avaritia#17]
As the title says. When I hit r on the item I have added a dire crafting table recipe to, it does show the needed inputs, but instead of the output it just shows a blank square. No error shows up in the zenscript code. There is no crash but here is something I found in the logs: [https://pastebin.com/xJ7ZM7x7](https://pastebin.com/xJ7ZM7x7).

This was on mc version 1.10.2:
Avaritia-1.10.2-2.1.0.1-universal.jar
CraftTweaker-1.10.2-3.0.24.jar
jei_1.10.2-3.14.7.419.jar

I can give a full modlist or pics if you think they would be helpful.
Thanks for the help :)

I have posted this issue on the jei issue tracker and mezz told me to post the issue here.

**Comment by matt091498** [comment]
Hey I just tested this with only a small amount of mods: [https://pastebin.com/dicH1Zuy](https://pastebin.com/dicH1Zuy).
The bug did not happen here. I can provide a full modlist for my other instance if you want. The only thing i can think of right now is that the item i was adding a recipe to was from Advanced Rocketry. In the instance with only a few mods I used an item from Draconic Evolution and it worked.

**Comment by matt091498** [comment]
Hey new update. I was able to add recipes to items and they would show up fine. Right now the only item that isn't working is the Liquid Fueled Engine from Advanced Rocketry. The other recipes I've added are also to Advanced Rocketry items, but these ones work fine. At this point I don't know what is going on.

**Comment by Morpheus1101** [comment]
Well thats good news, however, we'll still take a look at the JEI intergration just to make sure its not something that can happen again.

**Comment by Morpheus1101** [comment]
If this issue occurs again, please feel free to re-open this issue.
