### ISSUE TITLE
Can't Craft Ultimate Stew

### ISSUE THREAD

**Issue by Naini0712** [Morpheus1101/Avaritia#171]
Can't Craft Ultimate Stew
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Avaritia version: 1.12.2-3.3.0.33-universal
![2020-10-31_13 30 28](https://user-images.githubusercontent.com/55199184/97771203-ff1ec280-1b7d-11eb-876e-449d18f469fa.png)
![2020-10-31_13 30 30](https://user-images.githubusercontent.com/55199184/97771205-01811c80-1b7e-11eb-9189-69e90d61f721.png)
Mods
tinyprogressions-1.12.2-3.3.34-Release
Toast Control-1.12.2-1.8.1
torchmaster_1.12.2-1.8.1.81
TreeGrowingSimulator2017-1.0.1
Triumph-1.12.2-3.19.2
unloader-1.2.0
valkyrielib-1.12.2-2.0.20.1
voidislandcontrol-1.5.3
WailaHarvestability-mc1.12-1.1.12
WaterStrainer-1.12-3.2.0
woot-1.12.2-1.4.11
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
ActuallyAdditions-1.12.2-r151-2
aether_legacy-1.12.2-v1.4.4
AgriCraft-2.12.0-1.12.0-a6
AIImprovements-1.12-0.0.1b3
AkashicTome-1.2-12
AppleCore-mc1.12.2-3.2.0
AppleSkin-mc1.12-1.0.9
architecturecraft-1.12-3.98
astralsorcery-1.12.2-1.10.22
AttributeFix-1.12.2-1.0.4
AutoRegLib-1.3-32
Avaritia-1.12.2-3.3.0.33-universal
avaritiarecipemaker-1.0.0
badwithernocookiereloaded-1.12.2-3.3.16
base-1.12.2-3.13.0
Baubles-1.12-1.5.2
BetterAdvancements-1.12.2-0.1.0.77
BetterBedrockGenerator-1.12-6.1.1
BetterBuildersWands-1.12-0.11.1.245+69d0d70
BetterFps-1.4.8
BiblioCraft[v2.4.5][MC1.12.2]
BNBGamingCore-1.12.2-0.12.0
BNBGamingLib-1.12.2-2.17.6
bonsaitrees-1.1.4-b170
Bookshelf-1.12.2-2.3.590
Born In A Barn V1.8-1.12-1.1
Botania r1.10-363
BrandonsCore-1.12.2-2.4.18.210-universal
Chameleon-1.12-4.1.3
Chisel-MC1.12.2-1.0.1.44
ClayBucket-1.12-1.1
Clumps-3.1.2
CodeChickenLib-1.12.2-3.2.3.358-universal
CoFHCore-1.12.2-4.6.3.27-universal
CoFHWorld-1.12.2-1.3.1.7-universal
ContentTweaker-1.12.2-4.9.1
Controlling-3.0.8
CookingForBlockheads_1.12.2-6.5.0
CraftingTweaks_1.12.2-8.1.9
CraftPresence-1.12.2-1.6.1
CraftTweaker2-1.12-4.1.20
CTM-MC1.12.2-1.0.1.30
Cucumber-1.12.2-1.1.3
CustomMainMenu-MC1.12.2-2.0.9.1
CustomNPCs_1.12.2-(01Oct19)
DankNull-1.12.2-1.7.89
DefaultOptions_1.12.2-9.2.8
DimensionalEdibles-1.12.2-1.3.1
DimensionRules-MC1.12-1.1
DimensionStages-1.12.2-2.0.23
Draconic-Evolution-1.12.2-2.3.25.351-universal
Emojicord-1.12.2-1.1.1.39-universal
EnderCore-1.12.2-0.5.73
EnderIO-1.12.2-5.1.55
EnderTweaker-1.12.2-1.2.0
environmentaltech-1.12.2-2.0.20.1
ExtendedCrafting-1.12.2-1.5.6
ExtraBotany-r1.1-56
Fakename MC1.12.2 v1.2
FastLeafDecay-v14
fluxnetworks-1.12.2-4.0.14-31
foamfix-0.10.10-1.12.2
Forgelin-1.8.4
ForgeMultipart-1.12.2-2.6.2.83-universal
FpsReducer-mc1.12.2-1.14.1
FTBBackups-1.1.0.1
FTBLib-5.4.7.2
FTBQuests-1.9.0.12
FTBUtilities-5.4.1.130
FurnaceOverhaul-1.12.2-2.2.0
GameStages-1.12.2-2.0.123
GardenOfGlass
GasConduits-1.12.2-1.2.2
Guide-API-1.12-2.1.8-63
Harvest-1.12-1.2.7-20
Hats-1.12.2-7.1.0
HuntingDimension-1.12.2-1.0.42
Hwyla-1.8.26-B41_1.12.2
iChunUtil-1.12.2-7.2.2
ImmersiveEngineering-0.12-92
incontrol-1.12-3.9.16
industrialforegoing-1.12.2-1.12.13-237
infinitylib-1.12.0
InventoryTweaks-1.63
ironchest-1.12.2-7.0.72.847
ItemFilters-1.0.3.12
ItemStages-1.12.2-2.0.49
jei_1.12.2-4.15.0.291
jeiintegration_1.12.2-1.5.1.36
journeymap-1.12.2-5.7.1
justenoughdimensions-1.12.2-1.6.0-dev.20191019.172643
just-enough-harvestcraft-1.12.2-1.7.0
JustEnoughIDs-1.0.3-48
LagGoggles-1.12.2-5.8-132
Login_Shield-1.12.2-3-g7c6e7ac
Magneticraft_1.12-2.8.2-dev
Mantle-1.12-1.3.3.55
matc-1.0.1-hotfix
Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.2-9.8.3.390
modelloader-1.1.7
modtweaker-4.0.18
Modular Diversity-1.9
modularmachinery-1.12.2-1.10.0
moreoverlays-1.15.1-mc1.12.2
Morph-o-Tool-1.2-21
MrTJPCore-1.12.2-2.1.4.43-universal
MTLib-3.0.6
MysticalAgradditions-1.12.2-1.3.2
MysticalAgriculture-1.12.2-1.7.5
NoMoreRecipeConflict-0.13(1.12.2)
nonetherPortals_v1.0.0formc1.12.2
noRecipeBook_v1.2.2formc1.12.2
NuclearCraft-2.18o-1.12.2
OpenBlocks-1.12.2-1.8.1
OpenModsLib-1.12.2-0.12.2
OptiFine_1.12.2_HD_U_F5
OreStages-1.12.2-2.0.37
p455w0rdslib-1.12.2-2.3.161
Pam's HarvestCraft 1.12.2zf
pamsimpleharvest-2.0.0
phosphor-1.12.2-0.2.6+build50-universal
Placebo-1.12.2-1.6.0
plustic-7.1.6.1
ProjectRed-1.12.2-4.9.4.120-Base
ProjectRed-1.12.2-4.9.4.120-integration
Psi-r1.1-77
randompatches-1.12.2-1.21.0.0
randomtweaks-1.12.2-2.7.1.0
reauth-3.6.0
RebornCore-1.12.2-3.18.1.514-universal
RebornStorage-1.12.2-3.3.4.1
RecipeStages-1.1.3
RedstoneFlux-1.12-2.1.0.6-universal
refinedstorage-1.6.15
refinedstorageaddons-0.4.4
rsinfinitewireless-1.2
ScalingHealth-1.12.2-1.3.42+147
ServerObserver-1.12.2-1.0.8.41-universal
ServerTabInfo-1.12.2-1.2.6
SignPicture-1.12.1-2.8.1-universal
SilentLib-1.12.2-3.0.14+168
SimplyJetpacks2-1.12.2-2.2.14.67
SmoothFont-mc1.12.2-2.1.2
SpiceOfLife-mc1.12-1.3.12
StorageDrawers-1.12.2-5.4.0
Surge-1.12.2-2.0.77
TConstruct-1.12.2-2.13.0.179
tesla-core-lib-1.12.2-1.0.16
TexFix V-1.12-4.0
ThermalDynamics-1.12.2-2.5.5.21-universal
ThermalExpansion-1.12.2-5.5.4.43-universal
ThermalFoundation-1.12.2-2.6.3.27-universal
TickCentral-2.6
TinkerToolLeveling-1.12.2-1.1.0

**Comment by NameLord** [comment]
Are you blind?

**Comment by Morpheus1101** [comment]
Cannot reproduce. In the future please use something like pastebin to list all your mods.
