### ISSUE TITLE
About ad

### ISSUE THREAD

**Issue by 800805** [Morpheus1101/Avaritia#173]
Hello,I'm a Chinese Minecraft player.Can I advertise this wonderful mod to MCBBS(https://www.mcbbs.net) ?I'll let more people know it.MCBBS is the largest Minecraft forum in China,Many player are seeking good mods there.You know not all of them are good at English, they can't read your post (Even with Google translator) they need a Chinese translator.I'll mark you as the author .I'll NEVER claim it as mine, I just wanna translate it and let more people know it.Hope for your reply!Thank you!

**Comment by Morpheus1101** [comment]
No sorry, i would prefer you dont.

**Comment by 800805** [comment]
> No sorry, i would prefer you dont.

Why?I'm afraid you misunderstood me, I'll NEVER claim it as my own.The post in MCBBS will never be a release of your plugin, just an advertisement.I just wanna tell people there "Hey! there is a wonderful plugin called Avaritia and you can download it at Morpheus1101's Curseforge page!"I just wanna let more people know it, and nothing more.
