### ISSUE TITLE
(1.12.2) Boring food for cosmic meatballs

### ISSUE THREAD

**Issue by Maximus-Gaming** [Morpheus1101/Avaritia#174]
The cosmic meatballs recipe does not want to grab food from other mods. The ultimate stew has no problem doing so.
There should be multiple items tagged 'meat' as I have multiple food mods installed. The ultimate stew screenshot should illustrate that.
_Boring food is turned off._

![2021-03-02_12 53 10](https://user-images.githubusercontent.com/75425559/109646936-028c7f80-7b59-11eb-8a5e-5208eb0ee0bf.png)

![2021-03-02_12 54 13](https://user-images.githubusercontent.com/75425559/109646941-03bdac80-7b59-11eb-80d7-0b67599dbd1e.png)

**Comment by LnX-OrioN** [comment]
Change recipe by yourself ; )
