### ISSUE TITLE
rendering bug with cosmic shader effect on infinity armor + sword

### ISSUE THREAD

**Issue by xtrux** [Morpheus1101/Avaritia#177]
![image](https://user-images.githubusercontent.com/37349120/124322906-51214900-db4e-11eb-9b3d-3be2652a5b14.png)
on all modpacks i get this weird coloration with avaritia armor

i made a bug report for the 1.7.10 version a year ago
https://github.com/SpitefulFox/Avaritia/issues/138
for some reason the bug doesnt happen on new worlds until i restart the world
and it doesnt happen in galacticraft dimensions
![image](https://user-images.githubusercontent.com/37349120/124323076-a65d5a80-db4e-11eb-88b0-60a0d99afe21.png)
pack is project ozone 3 reloaded but it happens in every pack i have played with the mod. 
pc specs
rtx 2070
intel i7 8700k

**Comment by ryu777mtg** [comment]
I have had this issue as well but it's completely random and trying to enable/disable mods to figure out the cause.
@xtrux Can I ask what other mods you are using, what version of minecraft?
Are you using anything like Optifine, shaders, resourcepacks, etc?

**Comment by xtrux** [comment]
it happens on 1.7.10 and on 1.12.2 packs such as project ozone 2, project ozone 3, and enigmatica 2 expert

**Comment by Morpheus1101** [comment]
If this occurs in the 1.18x version, then re-open this ticket.
