### ISSUE TITLE
Why the world breaker doesnt destroy bedrock?

### ISSUE THREAD

**Issue by ghost** [Morpheus1101/Avaritia#178]

**Comment by TheRedDraqon** [comment]
I'm not sure...

I logged into a creative world just this morning about 2 minutes ago and wondered the same thing and the best guess I have is because it's avaritia's port to 1.10x minecraft and they state on curseforge it works differently on 1.7.10 and some features won't be available

**Comment by TheRedDraqon** [comment]
Only the hammer breaks bedrock. You can get the hammer by shift+right clicking the world breaker. This is deemed works as intented but in my opinion having to use the hammer which will break a large amount of bedrock is frustrating compared to the 1.7.10 world breaker being able to break bedrock more precisely
