### ISSUE TITLE
Could I advertise this wonderful mod to MCBBS

### ISSUE THREAD

**Issue by 800805** [Morpheus1101/Avaritia#179]
Hello,I'm a Minecraft player.I have played Minecraft with Avaritia Mod for a long time.I think this mod is so good!Could I advertise this wonderful mod to MCBBS(https://www.mcbbs.net) ?I'll let more people know it and mark you as the author .I'll NEVER claim it as mine, I just want to let more people know it,and I will let them download at your Curseforge page.Hope for your reply!Thank you!

**Comment by Morpheus1101** [comment]
While i appreciate the willingness to spread the mod elsewhere, i dont want it anywhere else, so No.

**Comment by 800805** [comment]
> While i appreciate the willingness to spread the mod elsewhere, i dont want it anywhere else, so No.

I only want to teach others how to use this mod and tell them who made this mod,is this ok?

**Comment by Morpheus1101** [comment]
Do so via a streaming platform or youtube
