### ISSUE TITLE
Endest Pearl Strange Crash

### ISSUE THREAD

**Issue by TheSpamMiner** [Morpheus1101/Avaritia#18]
Once I threw the pearl and it landed, it sat there for a second, then Minecraft immediately closed. That's a bit faster than most crashes I've seen, since it usually lags for a bit, then closes. Then the crash log was just the log, but at the end of the log it told me there was a file in the .minecraft folder with the crashlog in it, not the crash-logs folder.
Here's that log, hopefully you can figure out what it is, as it isn't a regular crashlog. https://pastebin.com/Spnam4B0

As a side note, not related to much of anything, my MC username is TheSpaMiner (intended to be Spam Miner with some letter overlap, not Spa Miner.) The letters at the end of the pastebin link are really close to Spam. I thought that was kinda funny.

**Comment by Morpheus1101** [comment]
There will be a new version i will push out in tne next day or so, please let me know if this issue still occurs.

**Comment by TheSpamMiner** [comment]
Alrighty then. I'll test it once I update.

**Comment by covers1624** [comment]
Has this issue occurred again? This seems like a driver issue.

**Comment by TheSpamMiner** [comment]
No, after this I figured I'd stay away from throwing it. And for some reason it sent me back about a real-time minute in my world, to just before I crafted the pearl.

**Comment by covers1624** [comment]
The reason for the roll back is that was no normal crash, The VirtualMachine java runs in crashed, from OpenAL, the audio library used by Minecraft, so MC didn't attempt to save anything. Im going to call this a driver issue, if it happens again feel free to comment here and we can investigate it further.
