### ISSUE TITLE
More of a request

### ISSUE THREAD

**Issue by star-krafter** [Morpheus1101/Avaritia#184]
Please make this available for Minecraft 1.7.10 so that someone has a chance of actually battling the titans.

**Comment by Morpheus1101** [comment]
https://www.curseforge.com/minecraft/mc-mods/avaritia

**Comment by NefariousIntent2** [comment]
> Please make this available for Minecraft 1.7.10 so that someone has a chance of actually battling the titans.

As an added note. The titans will kick you out of your world if you have avaritia armor on. The only way to bypass this is to decompile the .jar and remove the line of code, or remove it at runtime.
