### ISSUE TITLE
Model bug with infinity armor

### ISSUE THREAD

**Issue by UncoveredJager** [Morpheus1101/Avaritia#186]
When I wear infinity armor, the shader effect present acts as if I'm holding something when I'm not. if I pull out an item it connects and if I move it moves with my arms.

![Screenshot (877)](https://user-images.githubusercontent.com/72656904/146466004-50640722-2f40-4b6e-81c7-d78c2a4871bf.png)
![Screenshot (878)](https://user-images.githubusercontent.com/72656904/146466097-fcf3a086-f2c4-4308-a68a-dd740f3ee183.png)
![Screenshot (879)](https://user-images.githubusercontent.com/72656904/146466114-ec40c5f9-0e3d-4211-a47a-fc247b151713.png)

This is without any mods installed

**Comment by UncoveredJager** [comment]
Forgot to mention but I think is also a bug is that wings aren't visible from behind.
![Screenshot (880)](https://user-images.githubusercontent.com/72656904/146471844-78556be0-42ce-412c-90ac-b3cef020ac22.png)
![Screenshot (881)](https://user-images.githubusercontent.com/72656904/146471851-7e80e873-70c0-4085-a995-16bd2b849bb4.png)

**Comment by UncoveredJager** [comment]
Also forgot to mention that it is the latest 1.12.2*

**Comment by covers1624** [comment]
Do you have anything such as Optifine installed?
