### ISSUE TITLE
Neutronium compressor recipes are 10 times bigger than normal [Solved]

### ISSUE THREAD

**Issue by Al3ssan6r0** [Morpheus1101/Avaritia#189]
The neutronium compressor recipes are 10 times bigger the normal.

**Pictures:**

![bug 6](https://user-images.githubusercontent.com/102186855/163157739-06d7bd4e-c70f-4b23-9616-176e35856ab4.png)
![bug 5](https://user-images.githubusercontent.com/102186855/163157742-73afb476-1684-47fc-aaba-9453fdbb79f3.png)
![bug 4](https://user-images.githubusercontent.com/102186855/163157745-8827975d-adf9-4c8a-9725-fa2f8682fc2f.png)
![bug 3](https://user-images.githubusercontent.com/102186855/163157747-ad8171b7-0ca4-440d-9089-f61b7c28699c.png)
![bug 2](https://user-images.githubusercontent.com/102186855/163157751-489a8178-c05d-4832-a718-a1135e8ac951.png)
![Bug](https://user-images.githubusercontent.com/102186855/163157752-9b27dcc2-54e4-47f1-8257-05c29338efb5.png)

**Used Mods:**

![image](https://user-images.githubusercontent.com/102186855/163158740-34ef0308-629b-4f7b-9b22-2f9d0538fd42.png)

**I tried to:**

-Testing the recipe to see if is only a JEI bug [Bug persist and used a lot of ores].
-To run Avaritia in others instances (Using MultiMc)[Every time same bug].
-For 1 year I thought it was intentional but then I saw the ore costing list.

**Forge Version:**

Forge 14.23.5.2859 (I tried even others versions but this is the last I used)

**Avaritia Version:**

Avaritia 3.3.0.37 (like the forge version I tried even others versions but this is the last I used) [1.12.2]

**Comment by covers1624** [comment]
Avaritia scales the cost of these recipes based on the Mods you have installed.

If these recipes work as described in JEI, then there is no bug.
