### ISSUE TITLE
Please add clear function to dominate the sword of worldwide. 

### ISSUE THREAD

**Issue by love-code-yeyixiao** [Morpheus1101/Avaritia#190]
If you can do it, it is recommended that the right dominate the sword of worldwide labels on (NBT) can modify the mode, and add remove function.
The remove function can invoke the Entity object. (this implementation in 1.16.5 version, but I don't know 1.12 x version is there?)

I have been trying to under the branches of the SpitefulFox submitted, but he reply:
I don 't understand what you' r e have for. O.O

It a contributor like you want this implemented in one of the newer versions. This branch of the repo is for 1.7.10 version. Try date your issue home here:

https://github.com/Morpheus1101/Avaritia/issues

**Comment by covers1624** [comment]
I'm not sure what you are requesting.

The mod has been completely rewritten for 1.18. 

If your issue persists, please open a new issue.
