### ISSUE TITLE
[1.7.10]how i can get it right

### ISSUE THREAD

**Issue by windmoxa** [Morpheus1101/Avaritia#193]
the armor model is not following player's body,so how can i solve it?(the Adventure Backpack got the same isusse too,but i think they didn't import the api)
![2022-09-08_23 38 51](https://user-images.githubusercontent.com/109521949/189165614-4a34cde3-017f-436b-86a0-9da8658fada3.png)

**Comment by Morpheus1101** [comment]
This is for the 1.18x version an above .. 1.7.10 you'll need to go to spiteful fox repo
