### ISSUE TITLE
Licensing contradiction

### ISSUE THREAD

**Issue by tomodachi94** [Morpheus1101/Avaritia#194]
At the bottom of your readme, you have a copy of the MIT License. However, the CurseForge page has an "All Rights Reserved" license. Can you clarify the licensing of this mod?

See also: [SpitefulFox/Avaritia#154](https://github.com/SpitefulFox/Avaritia/issues/154)

**Comment by Morpheus1101** [comment]
It is now all set to MIT

**Comment by tomodachi94** [comment]
Alright, thanks!
