### ISSUE TITLE
Create zh_cn.json for 1.18.2

### ISSUE THREAD

**Issue by A-Black-Fish** [Morpheus1101/Avaritia#197]
<h1>English (英文)</h1>
All that can be translated are translated, if there are problems can be raised. (inherited from 1.12.2 of zh_CN.lang)
 (I don't know where to put the file, I can only put it here qaq)
For txt, you can change .txt to .json.

[zh_cn.txt](https://github.com/Morpheus1101/Avaritia/files/9901337/zh_cn.txt)

<h1>中文 （Chinese）</h1>
能翻译的都翻译了，有问题可以提出来。（ 继承自 1.12.2 zh_CN.lang）（我文件不知道放哪里，只能放这里qaq）
关于txt的问题，你可以把.txt改为.json

**Comment by molihuaacha** [comment]
大佬好

**Comment by A-Black-Fish** [comment]
什么大佬，我是笨比XD。
For txt, you can change .txt to .json.
关于txt的问题，你可以把.txt改为.json

**Comment by A-Black-Fish** [comment]
由于作者长时间无回应（将关闭此 issues）
