### ISSUE TITLE
Neutronium Compressor Dupe

### ISSUE THREAD

**Issue by BlakeBr0** [Morpheus1101/Avaritia#20]
By shift clicking a stackable item in the first slot of your hotbar while in the Neutronium Compressor gui and having the second hotbar slot be empty you can dupe items.

This can be easily fixed by correcting the values [here](https://github.com/Morpheus1101/Avaritia/blob/1.10.2-Full-Port/src/main/java/morph/avaritia/container/ContainerNeutroniumCompressor.java#L55) to 2 and 29.

**Comment by Morpheus1101** [comment]
Fixed in https://github.com/Morpheus1101/Avaritia/commit/3b2c251e67b7a0c52d7d2ed2ce9c77e12670e73a
