### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by yusofthecodemaster** [Morpheus1101/Avaritia#203]
how did you give the sword infinite attack damage

**Comment by NanashiTheNameless** [comment]
https://github.com/Morpheus1101/Avaritia/blob/07ce275b46e8afe4d932a0178777591794d7f612/src/main/java/morph/avaritia/util/DamageSourceInfinitySword.java#L11
https://github.com/Morpheus1101/Avaritia/blob/07ce275b46e8afe4d932a0178777591794d7f612/src/main/java/morph/avaritia/item/tools/ItemSwordInfinity.java#L13
