### ISSUE TITLE
can't seem to get extreme crafting scripts working

### ISSUE THREAD

**Issue by coaber** [Morpheus1101/Avaritia#204]
This may not be a bug, using Avaritia 4.0.0.4, and crafttweaker to create some custom extreme crafting recipes. previously i used the reforged port of avaritia which had very similar CT recipe callers for the  extreme crafting table. Two days ago i updated and this resulted in all my scripts being broken. I've talked with some of the CT staff to help me fix the scripts, but to no avail, perhaps asking here is a better option.
This is an example of what i used: `import mods.avaritia.ExtremeTableCrafting.addShaped;
                                                                  ExtremeTableCrafting.addShaped("name", output,[ ingredients]);`

**Comment by Morpheus1101** [comment]
We dont have support for CT in the 1.18x version
