### ISSUE TITLE
uncraftable infinity catalyst

### ISSUE THREAD

**Issue by vexzen23** [Morpheus1101/Avaritia#206]
the infinity catalyst is asking for items/mods i dont have and dont intend to use (ie thermal foundations tin singularity) thereby forcing me to download thermal foundation long enough to get the singularitys needed or cheat and i really dont want to cheat to get items that are so busted over powered cause then whats the point? i have currently added in thermal to get a singlarity but i have no plan to keep it installed also to my knowledge there doesnt appear to be a config file at all to change this and i dont understand why. should e of note i am playing on 1.18.2

**Comment by Morpheus1101** [comment]
When using Avaritia only and looking at recipe using JEI this is not a thing.  Are you using this in a pack?

http://imageshack.com/a/img924/9922/hOqjoe.png

**Comment by vexzen23** [comment]
> When using Avaritia only and looking at recipe using JEI this is not a thing. Are you using this in a pack?
> 
> http://imageshack.com/a/img924/9922/hOqjoe.png

its a pack i am putting together tho more for personal use i only have a few mods that add to the singularity pool like immersive engineering but it is asking for enderium and tin singul;arities which are from thermal which at the time i hadnt installed but after installing it there is still a modded item it is asking for but i cant identify as the space is blank
and again i cant locate the config file for avaritia to alter the asked for items

**Comment by Morpheus1101** [comment]
Having tested this while including Immersive Engineering, i can indeed see that this recipe issue occurs

**Comment by Morpheus1101** [comment]
We dont support this mod or MC version anymore
