### ISSUE TITLE
server1.18.2 NULLsingularity bug

### ISSUE THREAD

**Issue by hy9360** [Morpheus1101/Avaritia#207]
![image](https://user-images.githubusercontent.com/118053584/201471830-1b3731cf-6d3e-4061-a50a-f405b0c50248.png)
modlist

![화면 캡처 2022-11-12 202816](https://user-images.githubusercontent.com/118053584/201471858-9e84944d-1fee-41b8-801d-8c58446b2a5d.png)
all singularity are tured into NULLsingularity

**Comment by Morpheus1101** [comment]
Your meant to use a BLOCK of the resource not a single piece, so that picture is showing it work as intended
