### ISSUE TITLE
[1.10.2] Jump boost dosent work

### ISSUE THREAD

**Issue by Froggy800** [Morpheus1101/Avaritia#21]
The latest updates broke the infinity boots jump boost feature.
Also #14 was closed but it's actually not fixed (I don't know if it's better - for visibility - to comment on the issue itself or posting a new one. Please let me know)

**Comment by Morpheus1101** [comment]
re-comment on https://github.com/Morpheus1101/Avaritia/issues/14 and this can once again be re-looked at.
