### ISSUE TITLE
Item Error

### ISSUE THREAD

**Issue by Dr-WeiAL** [Morpheus1101/Avaritia#212]
![image](https://user-images.githubusercontent.com/47446553/208741344-d5a7cad6-023c-41fe-868c-379b46f91cd2.png)
What mods does Avaritia conflict with? Singularity all turned white, weapons were also added a layer of barrier
The light emitted also all turned white
I don't know if this is a known issue

**Comment by Aleon4201** [comment]
I saw white singularities too, but I solved it after I changed a video improve mod from rubidium to optifine.
Only avaritia and a required lib are also ok, so I think this conflict with rubidium (or magnesium that ports of sodium).

**Comment by Morpheus1101** [comment]
Its a Mod Conflict issue.
