### ISSUE TITLE
Where is the source code for the 1.18 version?

### ISSUE THREAD

**Issue by HumanGamer** [Morpheus1101/Avaritia#213]
Hello, I was going to try and fix #209 and do a PR but it seems the repository hasn't been updated in years. Where is the source code for the 1.18.2 version on curseforge?

If you have no plans to release the source code I could probably try and decompile the mod and fix it for my own playthrough, but then I wouldn't be able to release it to others.

**Comment by Morpheus1101** [comment]
Ask covers1624 or brandon3655
