### ISSUE TITLE
Sword of the Cosmos Doesn't one-hit kill in 1.18.2

### ISSUE THREAD

**Issue by BossOfKillers** [Morpheus1101/Avaritia#216]
Minecraft Version: 1.18.2
Mod Version: Avaritia-1.18.2-4.0.1.6-universal.jar

Tested with only JEI on, it says that attack damage is 12 and does as much as stated to the ender dragon.
The bow can one-shot it so the problem is only with the sword.
![Untitled](https://github.com/Morpheus1101/Avaritia/assets/105159832/f0e2423f-e2bb-41d9-b677-51848250e84f)

**Comment by Morpheus1101** [comment]
We dont support this mod or MC version anymore
