### ISSUE TITLE
Items don't have their tooltip lore in the 1.18.2 version, except the Skullfire Sword

### ISSUE THREAD

**Issue by EpicGaming11195** [Morpheus1101/Avaritia#217]
![image](https://github.com/Morpheus1101/Avaritia/assets/43396315/b33e8702-2fbb-4ff5-877f-17f5332db681)
![image](https://github.com/Morpheus1101/Avaritia/assets/43396315/ba315c2c-ea7b-4f20-a557-9d9270bc52c0)
![image](https://github.com/Morpheus1101/Avaritia/assets/43396315/137286d4-51d8-4fd1-a307-a83a0367f627)
![image](https://github.com/Morpheus1101/Avaritia/assets/43396315/6547cc78-a8a0-431c-a6ff-7536d177a60b)

**Comment by Morpheus1101** [comment]
We dont support this mod or MC version anymore
