### ISSUE TITLE
[1.10.2] Endest Pearl Issues

### ISSUE THREAD

**Issue by Morpheus1101** [Morpheus1101/Avaritia#22]
1.  Pearl Cannot be thrown but rather drops directly beneath where you throw pearl

2.  In 1.7.10 when pearl lands after being thrown a large black dome slowly forms an remains for  a short noticeable time length 1-2 IRL seconds, possibly longer creating a vacuum and exploding, the black dome does not occur, but particles do.

**Comment by Froggy800** [comment]
I just wanted to add that the black sphere does indeed appear, but it can apparently be seen only from specific points; the same applies for the implosion effect that is shown right before the blast
