### ISSUE TITLE
crash saying: Non [a-z0-9_.-] character in namespace of location: Avaritia:sounds.json

### ISSUE THREAD

**Issue by DrollestDuck88** [Morpheus1101/Avaritia#220]
Hi i've been making a little modpack... (my friend asked me too do that so i did and now i have the crash) 
the game starts and it comes to a crash state in the main loaded screen and you see the text in big square O...
please help me
Thanks 

here is the Crash and Logs 

[crash-2024-01-15_20.42.17-client.txt](https://github.com/Morpheus1101/Avaritia/files/13944462/crash-2024-01-15_20.42.17-client.txt)

[latest.log](https://github.com/Morpheus1101/Avaritia/files/13944461/latest.log)

**Comment by DrollestDuck88** [comment]
i forgot to say this is in 1.18.2...

**Comment by DrollestDuck88** [comment]
with forge 40.2.17

**Comment by Morpheus1101** [comment]
We dont support this mod or MC version anymore

**Comment by DrollestDuck88** [comment]
What is the issue?? Is it solvable?

**Comment by Morpheus1101** [comment]
This is happening because a mod added items/blocks/entities using uppercase letters in their names when they can only be lowercase (and should have been for years, if not strictly enforced until recently), hence the error message.


I would tru using the mod on its own..if it still occurs, nvr going to be fixed...if it dosent occur, than something is interfering with Avaritia.

**Comment by DrollestDuck88** [comment]
I have coded stuff using Kubejs but I don’t think I did any names with uppercase letters…

**Comment by DrollestDuck88** [comment]
> I have coded stuff using Kubejs but I don’t think I did any names with uppercase letters…

I verified some days ago and I am dumb… like really… (it’s a folder with an uppercase letter…)
I didn’t knew that (and I don’t know code very well + I don’t code every day for a living (not that poeple who do that are bad poeple but they will know what not to do like I did because I don’t know Java and JavaScript…)

**Comment by DrollestDuck88** [comment]
> This is happening because a mod added items/blocks/entities using uppercase letters in their names when they can only be lowercase (and should have been for years, if not strictly enforced until recently), hence the error message.
> 
> I would tru using the mod on its own..if it still occurs, nvr going to be fixed...if it dosent occur, than something is interfering with Avaritia.

I did an error and corrected it and it was working again… I just don’t know code and stuff
