### ISSUE TITLE
Neutronium compressor won't interact with other inventories

### ISSUE THREAD

**Issue by KDFireHero** [Morpheus1101/Avaritia#225]
I have added Avaritia to the Sky Factory 3 modpack, and The Neutronium compressor won't interact with any sort of item transport device.
EnderIO: Item Conduit
Translocators: Item Translocators
even Minecraft: Hoppers

[latest.log](https://github.com/user-attachments/files/17090091/latest.log)
 
if there is something I can change or add to the config to fix this it would be much appreciated
Thank you.

**Comment by Morpheus1101** [comment]
The Modpack is 8yrs old and we also don't support MC v1.10
