### ISSUE TITLE
[1.10.2] Multishot support

### ISSUE THREAD

**Issue by Skillotic0703** [Morpheus1101/Avaritia#24]
Can you add support for the multishot enchant (from CoFHCore) on the Longbow of the Heavens please?

**Comment by Morpheus1101** [comment]
I'll let covers take this one as he maintains that mod and knows all about it, but an interesting suggestion though.

**Comment by covers1624** [comment]
I don't really see the point as the bow insta kills things as it is. Plus it rains arrows anyway..

**Comment by NoplixDE** [comment]
Does it really kill insta? because I tried it on Ender Dragon and It didn't.
