### ISSUE TITLE
Rendering bug with Galacticraft

### ISSUE THREAD

**Issue by bortooo** [Morpheus1101/Avaritia#27]
![2017-05-29_22 03 40](https://cloud.githubusercontent.com/assets/28114042/26561187/97bae7a4-44bc-11e7-9fa7-efaa76f87979.png)
![2017-05-29_22 03 45](https://cloud.githubusercontent.com/assets/28114042/26561188/98998cb6-44bc-11e7-9572-4efd23d5610b.png)

Galacticraft: 1.10.2-Build 100
[Galacticraft issue](https://github.com/micdoodle8/Galacticraft/issues/2777)

**Comment by covers1624** [comment]
Err, unless Brandon did stuff, this is not fixed...

**Comment by Morpheus1101** [comment]
This will be looked into further and more detail for the 1.11.2 Full Port over

**Comment by p455w0rd** [comment]
on hold until such time as this issue is reproduced in 1.11.2+
