### ISSUE TITLE
Cannot figure out why this is not working

### ISSUE THREAD

**Issue by solunareclipse1** [Morpheus1101/Avaritia#31]
Trying to create recipes for a pack, and after double-checking, it seems fine. It is having an error parsing [creativerecipes.zs](https://pastebin.com/XGJDz5Gh) on line 8 I think. the exact error message is:

ERROR: Error parsing creativerecipes.zs:8 -- ] expected

I tried putting brackets in multiple locations on line 8 to no avail. Any ideas what the problem is?
I am using the latest versions of Avaritia, minetweaker, and modtweaker on curseforge.

**Comment by solunareclipse1** [comment]
Nevermind, I fixed it. I forgot the commas at the end of the lines for each recipe.

**Comment by IDKZAL** [comment]
Modpack? Link xD
