### ISSUE TITLE
[1.10.2] Crash? in Startup

### ISSUE THREAD

**Issue by StevieBranscum** [Morpheus1101/Avaritia#32]
When I start up the game, it gets past the first phase, then says that Avaritia is missing mods, yet at the bottom, no mods are missing. Pastebin won't allow the size of the log (not crash report). I'll try something else if need be.

**Comment by Morpheus1101** [comment]
Avaritia requires CodeChickenLib .. make sure you have it installed as well

**Comment by StevieBranscum** [comment]
I have that for EnderStorage. I got a screenshot.
![image](https://cloud.githubusercontent.com/assets/27051233/26810960/6cd08a80-4a34-11e7-9695-5c22806e4c2d.png)

**Comment by Morpheus1101** [comment]
What version of CodeChickenLib do you have?

**Comment by StevieBranscum** [comment]
CodeChickenCore (In case it helps): 2.4.0.101
CodeChickenLib: 2.5.2.198
Each are for 1.10.2

**Comment by StevieBranscum** [comment]
Most of my mods are from Hypothermia (1.4d) (Lost my original mods folder)

**Comment by Morpheus1101** [comment]
Your CCL vers is way out of date, it really needs updating as it was released before the 1st version of Avaritia was released

**Comment by StevieBranscum** [comment]
That didn't work.

**Comment by StevieBranscum** [comment]
![image](https://cloud.githubusercontent.com/assets/27051233/26811619/9d9a84fa-4a38-11e7-8c02-a9cb8ae66417.png)
Time in bottom right hand corner

**Comment by Morpheus1101** [comment]
Im using the latest vers of Avaritia myself with the latest version of CCL and it works perfectly fine, it is also in various modpacks without any issues, so i am unsure as to what is happening on your end for this to occur other than CCL is the only mod it depends on.

**Comment by StevieBranscum** [comment]
Want me to send you a copy of my mods folder?

**Comment by Morpheus1101** [comment]
Could u send me a list of what mods you have and there versions plz

**Comment by Morpheus1101** [comment]
![2017-06-06_16 26 34](https://cloud.githubusercontent.com/assets/10524952/26816463/0a375420-4ad5-11e7-8b68-c9a1cd217ec8.png)

I tested using Hypothermia pack from curse an added Avaritia and updated Forge & CCL and it works fine as you can see.

**Comment by StevieBranscum** [comment]
What I did was I copied the pack, with adding and deleting a few along the way, without any of the configurations. Do u mind if I send you a link via Google Drive?

**Comment by Morpheus1101** [comment]
Thats fine

**Comment by StevieBranscum** [comment]
Sorry about such a late response. Family had an issue with the A/C unit. Got it to work after a reinstallation of the mod and CodeChickenLib. Thanks for the help. I'll be sure to send anymore issues that may occur.
