### ISSUE TITLE
Some Singularities Won't Start Crafting

### ISSUE THREAD

**Issue by quixQuery** [Morpheus1101/Avaritia#34]
Singleplayer world, on the most recent Forge and Avaritia for 1.10 (details below).

Tried putting diamond blocks in the Neutronium Compressor, and singularity crafting wouldn't start. Also able to replicate the issue with Emerald, Copper, and Tin. 

However, Redstone, Gold, Iron, Lapis, and Quartz all work as intended.

![untitled](https://user-images.githubusercontent.com/26725961/26947557-bc873e7c-4c58-11e7-9008-42566a4c08ca.png)

(Forge 12.18.3.2254
Avaritia 1.10.2 - 2.1.2.1 - Universal)

**Comment by Morpheus1101** [comment]
The next version has recipes for the Diamond an Emerald singularities

**Comment by quixQuery** [comment]
I'm using latest 1.10 Mekanism on the new Avaritia version. Copper and Tin blocks are correctly registered in the ore dictionary, and singularity crafting still does not begin.

Though Diamonds and Emeralds are now working as intended!

**Comment by Morpheus1101** [comment]
I just tested this myself in Single and Multiplayer using Copper & Tin from mekanism and it works perfectly fine.

**Comment by togreglove** [comment]
I can't seem to get Blocks of Quartz to start compressing.

**Comment by Morpheus1101** [comment]
Are you using those made from Nether Quartz ?

**Comment by togreglove** [comment]
Yes, 2x2 nether quartz

**Comment by togreglove** [comment]
It just sits in the input slot and doesn't start a count.

**Comment by Morpheus1101** [comment]
I can confirm that it indeed dosent do a thing
