### ISSUE TITLE
[1.10.2] Copper & Tin from Mekanism fails to work in NeutroniumCompressor in SP

### ISSUE THREAD

**Issue by quixQuery** [Morpheus1101/Avaritia#36]
![testprofile](https://user-images.githubusercontent.com/26725961/27228498-7fcbc83e-526d-11e7-8811-ce7ccb700698.png)
Copper and Tin singularity crafting does not work in a testing environment. No config options have been tweaked. On Minecraft 1.10. Version numbers are visible in the above image.
![tincraftingnotfunctioning](https://user-images.githubusercontent.com/26725961/27228622-f6b04cea-526d-11e7-82d0-c1af453759b5.png)
![coppercraftingnotfunctioning](https://user-images.githubusercontent.com/26725961/27228649-1b5535d8-526e-11e7-8937-e39855148241.png)

**Comment by Lytearro** [comment]
You can use Mekanism's [Oredictionificator](http://wiki.aidancbrady.com/wiki/Oredictionificator) to convert them to something else as a work around.

**Comment by Morpheus1101** [comment]
Ok, ive retested using the latest version on Curse and in SinglePlayer those 2 dont work as you described, the compressor dosent see them as valid ore blocks. Being this is only with Mekanism, although classafying it as a bug, im not sure its my end thats the issue.

**Comment by Morpheus1101** [comment]
This is an issue with mekanism as they only add to the oredict if another mod adds one as well, so if no other mod in the pack adds copper or tin to the oredictionary mekanism wont register there's and since i use the oredict, that is why it breaks.

**Comment by p455w0rd** [comment]
I'll do this on our end..i'll just do a check for mek..if loaded, then add their ores to the oredict..why people are still using this buggy and unsupported mod is beyond me

**Comment by NoplixDE** [comment]
I think they are using this buggy mod because its so rich of Content People want stuff to work with i guess. :c

**Comment by quixQuery** [comment]
Hold up, they are registered to the ore dictionary though.

As blockCopper and blockTin.
![copperoredict](https://user-images.githubusercontent.com/26725961/27332566-e5bf35fa-5587-11e7-8449-cf9586419f50.png)
![tinoredict](https://user-images.githubusercontent.com/26725961/27332570-e78765d8-5587-11e7-83c2-6d679a6fb004.png)

**Comment by Morpheus1101** [comment]
If it was properly oredicted itd work since the way its coded is touse those registerd in tbe oredict, although mekanism may show an oredict name, it does not how ever register it with the mod on its own.

**Comment by Lytearro** [comment]
It's a shame that it's such a buggy mod because there is a lot there that I personally enjoy using and getting in to, but the thing I mentioned above is a universal work around, if you have other mods installed that are oreDict'd, then the Oredictionificator thing will convert them to something you "can" use, I usually only have to use it to remove NBT tags, but there is also a mod on my server that automatically converts multiples of ores from different mods to a single specific one, the ingots and stuff depending on which mod you use, will yield the different ingot types, so having Oredictionificator helps keep them as the same thing.

**Comment by p455w0rd** [comment]
I wholly agree. Mek is def one of my favorite 1.7.10 mods..it's def one of the better MC mods ever. Unfortunately for us, Aiden is a responsible person and values IRL more than modding lol (wish I had that level of discipline). At any rate..this will be fixed on our end in next update. :)
