### ISSUE TITLE
Unable to open the Neutronium Compresser GUI on server.

### ISSUE THREAD

**Issue by togreglove** [Morpheus1101/Avaritia#40]
I have the latest Twitch build on my server, and can pump items into the Neutronium Compresser and extract fine, but cannot open the GUI by clicking on it.

Tried this in a single player world with the exact same pack and it worked fine.

**Comment by Morpheus1101** [comment]
#26

**Comment by togreglove** [comment]
Sorry, thought I had seen the issue, but when I went back through closed tickets, I didn't see it. My bad.
