### ISSUE TITLE
[1.10.2] Avaritia breaks step assist from other mods

### ISSUE THREAD

**Issue by Froggy800** [Morpheus1101/Avaritia#41]
The mod is preventing the step assist from other mods to function at all; only the infinity boots are able to provide the player with the bonus. This bug is not present in version 2.1.2.1.
Tested with:
Avaritia 1.10.2-2.2.6
CCL 1.10.2-2.5.9.267

Mods I tested with:
enderio-1.10.2-3.1.193
uphillstepassist-0.0.5-1.10
ProjectE-1.10.2-PE1.3.1

**Comment by Morpheus1101** [comment]
hmm, fix a lot of bugs introduce some others.  thanks for the report.
