### ISSUE TITLE
[Suggestion] A "few" suggestions

### ISSUE THREAD

**Issue by TheUnderTaker11** [Morpheus1101/Avaritia#43]
I can split this up into more issues if you would like, but for the sake of the issue count I decided to put it in one issue.
* Mechanic- Have the World Breaker break the unbreakable blocks out of hammer mode. This suggestion is only for the ones following it, since you can't break some of the following blocks without having your world breaker in hammer mode. (Possibly destroying half of your base.)    
* Config Option- Add booleans in the config to disable the infinity armor and sword. (One for each piece preferably, or just one for all armor and one for the sword.) I think, due to the unkillable and the insta-kill everything trait of those two things, it scares away a lot of sever owners/pack makers that might add this mod. The mod could still be very useful for the next things even if the armor/sword gets disabled.
* New craftable items from other mods. Formatting is ExampleMod: Example item - Further explanation
  * [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers): **Creative Storage Upgrade** - This wouldn't even need to be super expensive with mods like Quantum Storage and Yabba adding that functionality, it just makes a storage drawer hold "near infinite storage", which would be amazing with the drawer controller.
  * [EnderIO](https://minecraft.curseforge.com/projects/ender-io): **Creative Capacitor Bank** - Can be broken by normal picks! Doesn't combine with other creative banks, and has a max output of 500k rf/t, doesn't output more by connecting to more sides of the block.
  * [Extra Utilities 2](https://minecraft.curseforge.com/projects/extra-utilities): **Creative Energy Source** - This block can only be broken with the hammer mode world breaker (wrenches/regular picks didn't work) and produces 16.8 million rf/t per side. This one is a bit much though.
  * Extra Utilities 2: **Creative Spikes** - Only broken with world breaker. Insta-kill spikes when touched, but mobs won't drop any items when killed by them, change log showing this [here](https://minecraft.curseforge.com/projects/extra-utilities/files/2338506)
  * Extra Utilities 2: **Creative Mill** - Only broken with world breaker. Generates 10k GP per block placed. This could easily be used if you use extra utilities for a lot of things, red coal, generating cobblestone, making RF, etc. It is very plausible that someone could need to make more than 1 of these if they have a large amount of automation and production.
  * [Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution): **Creative Flux Capacitor** - Allows infinite charging of items in your inventory.
  * [Thermal Expansion](https://minecraft.curseforge.com/projects/thermalexpansion): **Flux Capacitor (Creative)** - Same concept as the draconic one, but from thermal expansion.
  * Thermal Expansion: **Energy Cell (Creative) _and/or_ Creative Conversion Kit** - Can only be broken with world breaker. Energy cell has a max output of 25k rf/t per side connected. There is a bug where you also get the basic energy cell along with the creative one when breaking this with hammer-mode world breaker. The conversion kit turns any machine you right click into it's creative version.
  * [AE2](http://ae-mod.info/): **Creative Energy Cell** - Powers your whole ME system from AE. Didn't test what it can be broken with.
  * [Refined Storage](https://refinedstorage.raoulvdberge.com/): **Creative Controller** - Can be broken by normal picks! Refined storage only uses one controller, and it is what powers your whole system, so like the AE one having this will make your RS system not need power.
  * [Botania](http://botaniamod.net/): **The Everlasting Guilty Pool** - Infinite mana pool.
  * [RF Tools](https://minecraft.curseforge.com/projects/rftools): **Creative Powercell** - Can be broken by normal picks! Each one has an output of 20k rf/t per side, but is able to connect to your existing power storage multi-block from that mod. The way it works in RF Tools is you link each powercell with linking cards, so you are able to have cross dimensional "multiblock" power storage.
  * [Tinker's Construct](https://minecraft.curseforge.com/projects/tinkers-construct): **Creative Modifier** - Adds 1 extra modifier onto whatever tool you combine this with in the tool station/forge.
  * [PSI](http://psi.vazkii.us/): **Creative CAD Assembly** - Basically will let you make as powerful of spells as you want to from that mod.    
  * [Mekanism](https://minecraft.curseforge.com/projects/mekanism): **Creative Energy Cube** - Can be broken by normal picks! Outputs an ungodly amount of power. It somehow overrides the max I/O of a capacitor bank and fills it in almost no time. Might only want to enable this if there is no other creative energy production, and make this WAY more expensive.
  * Mekanism: **Creative Gas tank** - Can be broken by normal picks! Not exactly sure how to get gas in to make it have infinite of a certain type of gas, but JEI has a list of different gas options, so maybe recipes for gasses people want a lot of? Like the stuff used in the fusion reactor for example.
  * [Quantum Flux](https://minecraft.curseforge.com/projects/quantumflux): **Creative Quibit Cluster** - Can be broken by normal picks! Outputs 100k rf/t per side.
  * [Cyberwear](https://minecraft.curseforge.com/projects/cyberware): **Creative Capacitor** - Haven't really used this mod, but it should be an item that makes it so you don't ever have to charge yourself again.

Each of these recipes should be set so you can disable them in the config, so server owners who think any/all of this is too OP can just disable it.      
I have multiple blocks that do the same thing since people might not have one mod but not another, and it just adds more options. I would assume generally speaking each recipe would have end game parts from the mod it originates from. At least where applicable.

This took a lot longer to write and format than I expected...

**Comment by NoplixDE** [comment]
I already ask for the world breaker thingy and I still would like to use it. But to the other stuff  (recipes) I thinkt it should be done by modpack creator. Not this modpack maker. It just doesnt makes sense.

**Comment by TheUnderTaker11** [comment]
Well for one the original avaritia had recipes for some creative items, including the creative Thaumcraft wand as well.
Secondly how does it not make sense? The modpack makers can change the recipes as they please, and not ever average Joe is going to want to go in and add recipes for the things they want, and the ones they do might not be ridiculous enough. It took me long enough to write out all of those things, much less making each person take the time to figure out how to add recipes themselves, find all the items they want to add the the recipes, then add them into the game. Having an official recipe built into the mod for these things would make much more sense. The time can be spent once setting up the recipe and finding all the end game items that should be needed for the recipe, then everyone who downloads the mod can enjoy it without having to put in a bunch of legwork on their own. 
That's just what I think about it though, and a majority of the work these guys would need to put in is coming up with a good recipe for the items/blocks, otherwise I would just make a pull request myself.

**Comment by NoplixDE** [comment]
"I" Just think if you need Creative thinks it should be ur own job to make recipes and such. And if you need/Can craft Creative items. Then the "gameplay" has already failed in my eyes. In modpack like Project Ozone or any modpack with custom stuff okay, but as I can read out of your text U speak for more the "Vanilla" "Default" option guys. But why would they need Creative items? because the problem is, how should the Modmaker know how to make the Recipe? I mean he doesn't know what other mods u have installed so he could only use Vanilla items and from his mod. And that is in my eyes for Creative/Overpowered items way to less variety. He could definitely add some kind of "mod check loaded" to load the recipe but why should he make that work :P. I wouldn't be against your Idea I just think there is more important stuff. And as you said you can "pull request" and make it yourself and hope they accept it :P

**Comment by TheUnderTaker11** [comment]
As I said in the original, each recipe would use end game items from their origin mod where applicable, and otherwise just a ton of infinity ingots probably.    
If you are talking about "vanilla" it is virtually impossible to do anything in this mod with vanilla unless you spend like a year on the world. Why would it matter what other mods I have installed?    
"The 'gameplay' has already failed in my eyes" makes no sense to say about a mod that gives you a sword that literally one shots anything, and armor that makes you immortal to everything but the sword.
Something I loved about the original mod is this quote, "[The mod also adds recipes for the Creative Energy Cells from AE2 and TE. This may seem overpowered at first but at the point where the player is able to craft them it is not that useful to the player anymore except for the point that it does not need a refill.](https://ftbwiki.org/Avaritia)"    
On a side note, I feel like you have very much overestimated the difficulty of checking if a mod is loaded. The whole point of me not just coding it myself is I'm not a good source of what the recipes should be.    
I'm still confused about why you think this is an out of place thing to add, even though it was in the original 1.7.10 mod?     
[Here you can see the original creative  energy cell recipe.](https://ftbwiki.org/Creative_Energy_Cell).     
[Here was the creative Thaumcraft wand](http://ftb.gamepedia.com/Crystal_Studded_Cosmic_Neutronium_Wand)    
[The 1.7.10 version even had a infinite storage blood magic orb](http://ftb.gamepedia.com/Blood_Orb_of_Armok)    
It might be a bit more work but it's just a suggestion. If they decided on the recipes for whatever they want to add I would be willing to just code that in myself, as I have basically said before. Or they could just add it down somewhere in the todo list, either way, just putting out some things I would like to see implemented.

**Comment by NoplixDE** [comment]
I just feel like Minecraft Modded is getting out of hand and too Overpowered. Creative items should be only for Creative or you edit it yourself. Just ask KingLemming mod maker of all "Thermal" mods He says the same that there is too overpowered stuff. If you need the creative energy cell it failed already otherwise you made a modpack where only overpowered stuff with very hard recipes like PO2.
And I already made a Creative Energy Cell in my Modpack with many other Creative Items BUT they are 100x times harder to get than any other Recipes that u showed me.

Creative Energy Cell: https://gyazo.com/8351076b20d525ee21476a468e717001 
Creative Tank: https://gyazo.com/e40949407967d55332bf3e22fb62832e
Creative Upgrade Kit: https://gyazo.com/8e8af88bd00f36712b6c4b21e812bebd
Keep in mine there are custom Recipes for each item in it and I made them really hard. They may look harmless but I swear they are harde then PO2 Kappa mode.

**Comment by Morpheus1101** [comment]
I will not be adding recipes for all the creative stuff, to me that is taking things to far.

**Comment by covers1624** [comment]
Loked as per request
