### ISSUE TITLE
[1.11.2] Weapon/Items Not in JEI?

### ISSUE THREAD

**Issue by MokahTGS** [Morpheus1101/Avaritia#44]
Are items implemented yet in the 1.11.2 version?  I'm not seeing very much other than ingots and the crafting tables in JEI.

**Comment by Morpheus1101** [comment]
No. The full 1.11.2 with everything + more stuff for 1.11.2 will be coming in the next few days.

**Comment by MokahTGS** [comment]
Great,  thx for your work.
