### ISSUE TITLE
[1.11.2] Move away from null ItemStack

### ISSUE THREAD

**Issue by ExpensiveKoala** [Morpheus1101/Avaritia#46]
Use ItemStack.EMPTY instead. A lot of the code pertaining to Extreme crafting recipes use null ItemStacks.

**Comment by Morpheus1101** [comment]
This is on the todo list, thanks for letting gus know though :D

**Comment by p455w0rd** [comment]
I'm going to go ahead close this. The problem is fully resolved in dev and we'll be releasing our 1.11.2 port in the near future.
