### ISSUE TITLE
Crash on SpongeForge server when craft only is true

### ISSUE THREAD

**Issue by kaal-1** [Morpheus1101/Avaritia#47]
Forge 2281
Latest SpongeForge and latest Avaritia
It works fine, unless I set the config option to enable just the dire crafting table:
https://hastebin.com/axiqadanux.http

**Comment by p455w0rd** [comment]
I'm going to leave this to these guys. I, personally, refuse to support any bugs between Sponge/Bukkit/Spigot and Forge. SpongeForge is too under developed and we have tools to do most of what SF/Sponge would be needed for. Replicate this bug without a plugin API and I'll formally look into this.

**Comment by kaal-1** [comment]
Well, I've just found out it crashes the client... So with this option enabled you can't play in single player even

**Comment by Morpheus1101** [comment]
Sorry, there wont be support for anything else other then Forge directly

**Comment by kaal-1** [comment]
It's crashing even in single player

**Comment by Morpheus1101** [comment]
1.10.2 Works in SP and SMP using Forge .. I do not and will not support Spongeforge/spigot/bukkit.  1.11.2 isnt released yet and is still in development.

**Comment by Morpheus1101** [comment]
is this for MC 1.10.2 ?

**Comment by kaal-1** [comment]
Yes it's the 1.10.2 version (Avaritia-1.10.2-2.2.7).

**Comment by Morpheus1101** [comment]
The Mod is compiled against Forge *.2316 ... but we'll look into this error and get it sorted.

**Comment by Morpheus1101** [comment]
we've looked into this and there is just way to much that would have to be done to make this realistically usable in any environment, so we are removing this config option completely.

**Comment by covers1624** [comment]
Yeah, there is absolutely no point in keeping it, 1.10+ it would be an absolute nightmare to implement properly and honestly you are committing to pure MineTweaker anyway, just remove recipes and hide items, simple.
