### ISSUE TITLE
World breaker doesn't mine bedrock

### ISSUE THREAD

**Issue by AlexPlus117** [Morpheus1101/Avaritia#48]
World breaker, even if config is set to true, doesn't mine bedrock in its normal mode, but only in the hammer mode.

**Comment by Fundryi** [comment]
This is already reported, [(Read through here)](https://github.com/Morpheus1101/Avaritia/issues/3) it's not only bedrock normally u could mine any "unbreakable" block.

**Comment by Morpheus1101** [comment]
At this stage i have no desires to change how this works.
