### ISSUE TITLE
CraftTweaker issue

### ISSUE THREAD

**Issue by SFort** [Morpheus1101/Avaritia#52]
If i attempt to add or a remove a recipe it returns:
"No such member: avaritia"
e.g.
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_helmet>);

Avaritia-1.11.2-3.1.1.5-universal
modtweaker-3.0.2

**Comment by Fundryi** [comment]
U need CraftTweaker if I remember.

**Comment by SFort** [comment]
My mistake.
I had that installed too tho
CraftTweaker-1.11.2-3.0.26

**Comment by Morpheus1101** [comment]
Can you provide a copy of the script your using plz?

**Comment by SFort** [comment]
Sure thing.
(Changed it to a txt since github does not accept .zs)
[x_Avaritia.txt](https://github.com/Morpheus1101/Avaritia/files/1306582/x_Avaritia.txt)

**Comment by Morpheus1101** [comment]
Would seem 1.11.x has no support, this will be looked into as soon as we can, howeevr with the 1.12 vers dropping soon'ish it may not be added

**Comment by Morpheus1101** [comment]
1.11.2 is no longer being supported.
