### ISSUE TITLE
More singularities and stuff

### ISSUE THREAD

**Issue by Trinsdar** [Morpheus1101/Avaritia#53]
Could you add more singularities, the eternal singularity, and a direautocrafting tab since the mods with those haven't updated to newer versions?

**Comment by p455w0rd** [comment]
no, no, and uwot?

**Comment by Morpheus1101** [comment]
There will be no more singularities added and i dont follow your meaning for "direautocrafting tab"

**Comment by p455w0rd** [comment]
i do believe "direautocrafting tab" is "direautocrafting table"...this will not be added in the main mod if at all
