### ISSUE TITLE
Jei singularity issue in 1.10

### ISSUE THREAD

**Issue by Trinsdar** [Morpheus1101/Avaritia#54]
When Jei and avaritia are loaded together, I can't click on singularities and see how many blocks they take.

I am using  Avaritia-1.10.2-2.2.7-universal and jei_1.10.2-3.14.7.416

**Comment by Morpheus1101** [comment]
This wasn't implemented until 1.11.2.  1.10.x is no longer supported so a backport of this feature wont be done.
