### ISSUE TITLE
Hoe Effects Issues

### ISSUE THREAD

**Issue by DYColdWind** [Morpheus1101/Avaritia#57]
Such as the title
Now a Hoe of the Green Earth bit weak. :)
So, can add some special effects for it.For example: ripening or some treatment（such as：purification Zombie Villager or heal the player）?

**Comment by Morpheus1101** [comment]
It does all its supposed to, it s hoe that affects the earth an tills either a small or large area, i have no further plans at this stage for adding anything else to the hoe
