### ISSUE TITLE
Config options

### ISSUE THREAD

**Issue by Zer0Lyfe** [Morpheus1101/Avaritia#58]
would it be possible to add the option to disable the use of other mods items like Binnie's mods, forestry, Actually Addictions, etc as there is no way apart from disabling the actual mods.

**Comment by Morpheus1101** [comment]
In what sense do you mean an option to disable the use of other mods?

**Comment by Zer0Lyfe** [comment]
something like this that was in the 1.7 version:
![image](https://user-images.githubusercontent.com/28994351/34034489-c1861b04-e1b9-11e7-99ad-b4ec6f2dc4aa.png)

**Comment by Morpheus1101** [comment]
we'll take a look an see what can be done.

**Comment by Zer0Lyfe** [comment]
thank you morpheus.

**Comment by Morpheus1101** [comment]
i've discussed this and its not something that is now practical, perhaps in future versions it maybe.

**Comment by Zer0Lyfe** [comment]
ok no problem.
