### ISSUE TITLE
Thermal Dynamics: Servos cannot extract items from the Avaritia machines

### ISSUE THREAD

**Issue by a20eac1d** [Morpheus1101/Avaritia#59]
What is happening:
Items will not be extracted and transported away.

Screenshot:
https://i.imgur.com/me4H807.png

**Comment by Morpheus1101** [comment]
Somewhere in the update this got broken, i can confirm through testing this is actually a thing.

**Comment by Morpheus1101** [comment]
Fixed in https://github.com/Morpheus1101/Avaritia/commit/ffca07e385bbc8762668f1b5e95b26c3d40539da
