### ISSUE TITLE
Getting an Error trying to add recipes via crafttweaker

### ISSUE THREAD

**Issue by Saereth** [Morpheus1101/Avaritia#6]
ERROR: Error executing avaritia.zs: minetweaker.MineTweakerAPI.getIjeiRecipeRegistry()Lminetweaker/api/compat/IJEIRecipeRegistry;

 Avaritia 2.0.5
JEI 3.14.7.416
Crafttweaker 3.0.16.

 here is my lastest logfile:
https://www.dropbox.com/s/z5kphkkwgatr1lt/latest.log?dl=0

and the script in question (Avaritia.zs):
https://hastebin.com/usasixidir.http

**Comment by brandon3055** [comment]
Whats with the * 1 on <wct:infinity_booster_card> ? I dont actually know if thats valid script syntax but ether way its not needed because the default is 1.

**Comment by Morpheus1101** [comment]
Testing this and removing the *1 in your script everything works as it should
![2017-03-14_14 28 17](https://cloud.githubusercontent.com/assets/10524952/23885952/c03e5ca0-08c2-11e7-9fad-94aa0e1b96fe.png)

**Comment by Saereth** [comment]
Just came here to say thanks for looking into this, I was still on MT lib 1.0.0, updated to 1.0.1 allowed it to work with the * 1 or without it for me. Just reporting back in case anyone else runs into this.
