### ISSUE TITLE
Fancy Block Particles

### ISSUE THREAD

**Issue by a20eac1d** [Morpheus1101/Avaritia#60]
Avaritia (rendering?) breaks the mod "Fancy Block Particles" (https://minecraft.curseforge.com/projects/fancy-block-particles).

The animation of breaking blocks (all blocks) will stop playing after a few ticks:

https://gfycat.com/ImpossibleAdoredBuzzard

**Comment by covers1624** [comment]
I really don't see how avaritia could be causing it.. but I'll investigate.

**Comment by a20eac1d** [comment]
Enabling Avaritia causes the issue to appear.
Unloading it fixes it.

So it definitely IS that cause, but as to how ...

**Comment by Morpheus1101** [comment]
Can you replicate this with just Avaritia and fancyblockparticles ?

**Comment by Morpheus1101** [comment]
Unable to Reproduce in Dev and Out. Testing concludes mod interaction works as intended, i suggest you try removing other mods untill the issue stops occuring.
