### ISSUE TITLE
[1.12.2] Axe has the Hoe recipe in addition to its own

### ISSUE THREAD

**Issue by Zsashas** [Morpheus1101/Avaritia#67]
Meanwhile the Hoe is currently uncraftable.

![2017-12-17_09 20 56](https://user-images.githubusercontent.com/6917535/34082030-d270f10c-e30b-11e7-832a-66b4df1c6867.png)
![2017-12-17_09 20 59](https://user-images.githubusercontent.com/6917535/34082031-d287b586-e30b-11e7-829e-7727816703a1.png)

**Comment by Morpheus1101** [comment]
Fixed in https://github.com/Morpheus1101/Avaritia/commit/ffca07e385bbc8762668f1b5e95b26c3d40539da
