### ISSUE TITLE
[Suggestion]Minetweaker/Crafttweaker xp crafting support

### ISSUE THREAD

**Issue by TokkenGmr** [Morpheus1101/Avaritia#7]
Would it be possible to add support for the xp crafting option in crafttweaker? I know that there is support for crafttweaker but it is done from you end I think here is an example in a regular crafting bench
http://pastebin.com/pjTLub6p
Just thought it could be cool to add

**Comment by Morpheus1101** [comment]
Thankyou for the suggestion, but at this stage this isnt something i have any plans at wanting to add support for.
