### ISSUE TITLE
[1.12.2] Frame drops when using Extreme Crafting Table

### ISSUE THREAD

**Issue by DeadSix27** [Morpheus1101/Avaritia#78]
Whenever I access the crafting table it makes my frame rate go down to 1.

I also made a small video showing it: https://www.youtube.com/watch?v=zI9jzZ-9WTI

Full mod list: https://pastebin.com/kEybJF3C

Log output around the time of accessing the table: _I was going to add this, but there was nothing in there apart from "Saving chunks for level.."_

**Comment by Morpheus1101** [comment]
Since my Testing in large packs i have dosent re-produce this issue, Could you provide a lin k in which to grab this pack either from curse or via a twitch export as i firmly believe this is something to do with another mods interaction, but more testing is needed.

**Comment by DeadSix27** [comment]
@Morpheus1101 It's a kitchen sink I made myself, I can try to narrow it down to see if a specific mod causes this, its ~280 mods.. so it will take me a while. I opened this issue in the hope that this may sound familiar to you, so that I won't have to do that :P so yeah.. give me a few days and I'll come back to this,

However I made the twitch export anyway, this has no configs or anything, just the mods. You'll probably have to get rid of advanced rocketry and pneumatic craft (both require some dimension/other configs changed to work) but they are unlikely to cause this issue anyway: [custom_pack-1.0.zip](https://github.com/Morpheus1101/Avaritia/files/1649356/custom_pack-1.0.zip)

**Comment by DeadSix27** [comment]
@Morpheus1101 Alright, narrowed it down, its [NoMoreRecipeConflict-0.9(1.12).jar](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict), I was suspecting this mod from the start...
It's also not build against 1.12.2.. and has no source code available to us (it seems).

**Comment by Morpheus1101** [comment]
ok, thanks for letting us know.

**Comment by Morpheus1101** [comment]
Re-Opening this issue so i know to keep checking on it due to it still persisting.

**Comment by p455w0rd** [comment]
closing, cuz if it's on their end, no reason to clutter this tracker..if it persists, a new issue can be opened and we can go from there
