### ISSUE TITLE
Draconic Support?

### ISSUE THREAD

**Issue by 1matto** [Morpheus1101/Avaritia#8]
Is it possible for you to add support for Draconic Evolution in the mod since Brandon ported the base 1.10 version of Avaritia?

**Comment by Morpheus1101** [comment]
In what regards are you wanting Draconic Support?

**Comment by 1matto** [comment]
Like making use of the dire crafting table and the singularitys into making items from both mods but make it an option if the player wants this integration

**Comment by 1matto** [comment]
Might be a good thing to add for FTB Beyond expert mode when that gets released

**Comment by Morpheus1101** [comment]
FTB have said they wont be using Avaritia in any of their future packs.  But the mod is about to get a complete re-write starting very shortly, but adding in some avaritia stuff to make some DE stuff ... tbh im not so sure im wanting to do this, but i'll run it past Brandon.

**Comment by 1matto** [comment]
I would like to see which direction you will go from the re-write

**Comment by Morpheus1101** [comment]
Ok, so the only 2 things from Draconic that i'll incorporate into Avaritia will be the 2 Creative items .. being the Creative RF Source & Creative Flux Capacitor .. Recipes ive yet to determine, but it will of course require the DireCrafting table and be very hellishly expensive to make

**Comment by 1matto** [comment]
That may work

**Comment by Morpheus1101** [comment]
After further discussion with Covers & Brandon i've decided to not add any draconic support.
