### ISSUE TITLE
Custom Recipe

### ISSUE THREAD

**Issue by Confluxes** [Morpheus1101/Avaritia#83]
I'm trying to make a custom recipe and cant seem to get it to work and my guess would be the format is wrong so if anyone could let me know what I'm doing wrong that would be super, thanks.

my script - https://pastebin.com/eBqm4MNF

**Comment by Morpheus1101** [comment]
mods.avaritia.ExtremeCrafting.addShaped("name",output, ingredients);

**Comment by covers1624** [comment]
You are not using craft tweaker correctly, please read the documentation on how to use craft tweaker. Unless you have defined variables in your script, to reference an item you need to do `<domain:name:meta>`

**Comment by Confluxes** [comment]
i was using variables and i figured it out, it was correct it just didn't work on minecraft 1.10 for some reason

**Comment by Morpheus1101** [comment]
Crafttweaker for 1.10 is different to 1.12
