### ISSUE TITLE
[1.12.2] Infintiy Helmet & Boots loses correct texture with other enchanted Armour

### ISSUE THREAD

**Issue by Wireless4024** [Morpheus1101/Avaritia#84]
texture bug 

![image](https://user-images.githubusercontent.com/36229606/36348443-4944d790-14a2-11e8-9229-47387454e1a8.png)

**Comment by p455w0rd** [comment]
I looked into it..this is beyond me

**Comment by covers1624** [comment]
I found it! Fixed in dev.
Vanilla doesn't properly pop blend state around rendering enchantment glints on armor.

**Comment by Morpheus1101** [comment]
Fixed in Avaritia-1.12.2-3.3.0.28
