### ISSUE TITLE
Wrong number of items required in custom recipes [1.12.2]

### ISSUE THREAD

**Issue by Diamondblockmc** [Morpheus1101/Avaritia#90]
I've setup a steel singularity using the crafttweaker stuff. In the zs it is set to need 8500 items, but the compressor says that it needs 50000.

Script: https://pastebin.com/ia4gb1DA
Log: https://pastebin.com/zZtF9Lkv

MC version: 1.12.2
Forge version: 14.23.2.2619
Mod version: 3.2.0.013

**Comment by Morpheus1101** [comment]
because 8500 is the default amount IF you were to have Avaritia on its own, you then have the various multipliers on top of that

**Comment by Diamondblockmc** [comment]
I think it's 7500, but thank you anyway. I feel like it should be clarified on the curseforge page though.

**Comment by covers1624** [comment]
You can specify as an extera argument at the end for exact values, so the balance calculator won't touch it.

**Comment by Diamondblockmc** [comment]
Do you mean the use scaling boolean?

**Comment by covers1624** [comment]
Yes, https://github.com/Morpheus1101/Avaritia/blob/master/src/main/java/morph/avaritia/compat/crafttweaker/Compressor.java#L31
