### ISSUE TITLE
[Config]Break Bredrock - false doesnt work

### ISSUE THREAD

**Issue by xILikepuddingx** [Morpheus1101/Avaritia#92]
I change the config break bedrock from true to false, but it doesnt work

https://screen.pudding.tk/wy877wb5t1.png

Mod: Avaritia-1.12-3.2.0.13-universal
Modpack: Modern Skyblock 3

**Comment by Cyancraft** [comment]
This may not be a bug. It's a problem with Avaritia Tweaks forcing an enable:

`B:makeWorldBreakerGreatAgain=true`

Try disabling that.

**Comment by p455w0rd** [comment]
Just did a ton of testing. Appears @Cyancraft is correct.
