### ISSUE TITLE
Infinity Bow random hit player while shooting

### ISSUE THREAD

**Issue by Wireless4024** [Morpheus1101/Avaritia#94]
https://www.youtube.com/watch?v=WHg-vQMaxwg

**Comment by Morpheus1101** [comment]
I suspect this occurs when shooting straight down an u get hit when the rain of arrows is triggered

**Comment by armkrub** [comment]
but shoot target doesn't near my self

**Comment by covers1624** [comment]
Cant reproduce this in dev.
