### ISSUE TITLE
Problem with crafting

### ISSUE THREAD

**Issue by HurtsAsHell** [Morpheus1101/Avaritia#97]
can u tell me what is the problem?
mods.avaritia.Compressor.add(<<avaritia:singularity:13>>, 4650, <<thermalfoundation:storage:6>>, false);

 a method available but none matches the parameters (ZenTypeNative: crafttweaker.item.IItemStack, int, ZenTypeNative: crafttweaker.item.IItemStack, bool)
This is usually an error in your script, not in the mod
add(string, ZenTypeNative: crafttweaker.item.IItemStack, int, ZenTypeNative: crafttweaker.item.IIngredient, Optional bool)

**Comment by wamc2017** [comment]
I think you'll have to add the recipe name...

`mods.avaritia.Compressor.add("someRecipeName", <avaritia:singularity:13>, 4650, <thermalfoundation:storage:6>, false);`

**Comment by HurtsAsHell** [comment]
yes, thanks

**Comment by HurtsAsHell** [comment]
C
