### ISSUE TITLE
Bug nas texturas 

### ISSUE THREAD

**Issue by ZkilleMito** [Morpheus1101/Avaritia#98]
Bom instalei certinho de primeira, pediu para instalar junto com o mod: CodeChickenLib-1.12.2-3.1.6.339-universal, baixei, instalei, abriu de boa mas quando vou pegar os itens, ficarao assim 
![print](https://user-images.githubusercontent.com/38038982/38249346-c6fab6a4-3721-11e8-9fe3-3171cf62aa2d.jpg)

Já pesquisei muito sobre isso e não achei nada Então estou criando esse tópico para ver se alguém possa me ajudar a resolver esse problema, Espero retorno

**Comment by Morpheus1101** [comment]
Quais outros mods você instalou com o Avaritia?

**Comment by ZkilleMito** [comment]
![2](https://user-images.githubusercontent.com/38038982/38285794-4c79d3a2-3798-11e8-8a68-a5760a6fa0b2.jpg)
Esses são os outros mods que eu uso

**Comment by Morpheus1101** [comment]
Este problema ocorre apenas com Avaritia e codechickenlib instalado?

**Comment by ZkilleMito** [comment]
não sei dizer, sempre que instalo somente o avaritia Pede o CodeChickenLib 3.1.4 ou mais(estou usando a versao 3.1.6)

**Comment by Morpheus1101** [comment]
BetterPVP se bem me lembro é um mod antigo que não está mais sendo atualizado ativamente.

A primeira coisa que posso sugerir é remover os mods 1 de cada vez até que o erro não ocorra mais

**Comment by ZkilleMito** [comment]
Ok, irei ver agr, Obrigado por me ajudar, pesquisei muito e não tive sucesso
Espero que seja esse problema

**Comment by Morpheus1101** [comment]
Vamos investigar e ver o que pode ser encontrado

**Comment by ZkilleMito** [comment]
Bom, só deixei o mod avaritia Quando iniciei já de cara apareceu esse erro
![2](https://user-images.githubusercontent.com/38038982/38287103-4897c04e-379f-11e8-9245-a2b3f7746e56.jpg)
Instalei a ultima versão que é a CodeChickenLib-1.12.2-3.1.6.339-universal
Inicio de boa quando abri estar com o mesmo problema
![24](https://user-images.githubusercontent.com/38038982/38287133-67ff7e18-379f-11e8-8606-d2368254388b.jpg)

**Comment by ZkilleMito** [comment]
Instalei ate a versão um pouco antiga CodeChickenLib-1.12.2-3.1.5.331-universal, Mesmo assim estar com o mesmo erro das texturas

E aqui que eu peguei os dois codechickinlib https://minecraft.curseforge.com/projects/codechicken-lib-1-8/files

**Comment by ZkilleMito** [comment]
se puder me dar um retorno pf

**Comment by Morpheus1101** [comment]
Isso ainda ocorre na última versão?

**Comment by covers1624** [comment]
Please provide a debug crash report. The Minecraft wiki should have an entry on it in your language. I suspect this has something to do with shaders not being properly supported on your system.

**Comment by covers1624** [comment]
This is likely due to outdated video card drivers or an extremely old system that doesn't support shaders, sadly nothing i can do.
